-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2011, 2014                      
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

UPDATE CALENDAR.CA_SCHEMA SET DBSCHEMAVER = '4', RELEASEVER = '4.0.0.0.0' WHERE COMPKEY = 'CALENDAR';

CREATE TABLE CALENDAR.CA_EVENTTAG (
	TAG_UUID		VARCHAR(36)	 NOT NULL,
	CALENDAR_UUID	VARCHAR(36)	 NOT NULL,
	EVENT_UUID		VARCHAR(36)	 NOT NULL,
	NAME	    	VARCHAR(256) NOT NULL,
	MODIFIEDON	    TIMESTAMP	 NOT NULL
)TABLESPACE CALENDARREGTABSPACE;
CREATE INDEX CALENDAR.CA_EVTAG_EVID_IDX ON CALENDAR.CA_EVENTTAG(EVENT_UUID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVTAG_CALID_IDX ON CALENDAR.CA_EVENTTAG(CALENDAR_UUID, NAME)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVTAG_NAME_IDX ON CALENDAR.CA_EVENTTAG(NAME, CALENDAR_UUID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE UNIQUE INDEX CALENDAR.CA_EVTAG_NAME_EVID_IDX ON CALENDAR.CA_EVENTTAG(NAME, EVENT_UUID)TABLESPACE CALENDARINDEXTABSPACE;

CREATE TABLE CALENDAR.CA_EVENTTAGAGG (
	TAGAGG_UUID		VARCHAR(36)	 NOT NULL,
	CALENDAR_UUID	VARCHAR(36),
	NAME	    	VARCHAR(256) NOT NULL,
	TOTAL			INTEGER		 NOT NULL,
	LASTUSED	    TIMESTAMP	 NOT NULL
)TABLESPACE CALENDARREGTABSPACE;
CREATE INDEX CALENDAR.CA_EVTAGAGG_CALID_IDX ON CALENDAR.CA_EVENTTAGAGG(CALENDAR_UUID, TOTAL)TABLESPACE CALENDARINDEXTABSPACE;
CREATE UNIQUE INDEX CALENDAR.CA_EVTAGAGG_CALID_NAME_IDX ON CALENDAR.CA_EVENTTAGAGG(CALENDAR_UUID, NAME)TABLESPACE CALENDARINDEXTABSPACE;

CREATE TABLE CALENDAR.CA_EVENTCOMMENT (
	COMMENT_UUID	VARCHAR(36)	 NOT NULL,
	CALENDAR_UUID	VARCHAR(36)	 NOT NULL,
	EVENT_UUID		VARCHAR(36)	 NOT NULL,
	CREATEDBY		VARCHAR(36)	 NOT NULL,
	CREATEON		TIMESTAMP	 NOT NULL,
	CONTENT	    	CLOB         NOT NULL
)TABLESPACE CALENDARREGTABSPACE;
CREATE INDEX CALENDAR.CA_EVCMT_EVID_IDX ON CALENDAR.CA_EVENTCOMMENT(EVENT_UUID)TABLESPACE CALENDARINDEXTABSPACE;

ALTER TABLE CALENDAR.CA_EVENTTAG 
	ADD (CONSTRAINT CA_EVTAG_PK PRIMARY KEY (TAG_UUID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);

ALTER TABLE CALENDAR.CA_EVENTTAGAGG 
	ADD (CONSTRAINT CA_EVTAGAGG_PK PRIMARY KEY (TAGAGG_UUID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);

ALTER TABLE CALENDAR.CA_EVENTCOMMENT 
	ADD (CONSTRAINT CA_EVCMT_PK PRIMARY KEY (COMMENT_UUID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);
	
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_EVENTTAG TO SNCOMMUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_EVENTTAGAGG TO SNCOMMUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_EVENTCOMMENT TO SNCOMMUSER_ROLE;

COMMIT;

QUIT;