-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2012, 2014                        
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

delete from CALENDAR.CA_DELETION_HISTORY;
commit;

delete from CALENDAR.CA_EVENTTAGAGG where CALENDAR_UUID is null;
commit;

update CALENDAR.CA_CALENDAR set ORG_ID = ' ' where ORG_ID is NULL or ORG_ID = '';
commit;

alter table CALENDAR.CA_EVENTTAGAGG modify (CALENDAR_UUID varchar(36) not null);
commit;

alter table CALENDAR.CA_CALENDAR modify (ORG_ID varchar(36) not null);
commit;

-- add CALENDAR_UUID column to CA_DELETION_HISTORY table
alter table CALENDAR.CA_DELETION_HISTORY add (CALENDAR_UUID varchar(36) not null);
commit;

-- add ORG_ID column for all tables
alter table CALENDAR.CA_MEMBERSHIP add (ORG_ID varchar(36) default ' ' not null);
alter table CALENDAR.CA_EVENT add (ORG_ID varchar(36) default ' ' not null);
alter table CALENDAR.CA_EVENTINSTANCE add (ORG_ID varchar(36) default ' ' not null);
alter table CALENDAR.CA_SUBSTITUTION add (ORG_ID varchar(36) default ' ' not null);
alter table CALENDAR.CA_RECURRENCE add (ORG_ID varchar(36) default ' ' not null);
alter table CALENDAR.CA_EVENTINFO add (ORG_ID varchar(36) default ' ' not null);
alter table CALENDAR.CA_EVENTTAG add (ORG_ID varchar(36) default ' ' not null);
alter table CALENDAR.CA_EVENTTAGAGG add (ORG_ID varchar(36) default ' ' not null);
alter table CALENDAR.CA_EVENTCOMMENT add (ORG_ID varchar(36) default ' ' not null);
alter table CALENDAR.CA_EVENTFOLLOWING add (ORG_ID varchar(36) default ' ' not null);
alter table CALENDAR.CA_DELETION_HISTORY add (ORG_ID varchar(36) default ' ' not null);
commit;

-- migrate ORG_ID data to all tables
delete from CALENDAR.CA_MEMBERSHIP where not exists (select 1 from CALENDAR.CA_CALENDAR cal where cal.CALENDAR_UUID = CALENDAR.CA_MEMBERSHIP.CALENDAR_UUID);
update CALENDAR.CA_MEMBERSHIP set ORG_ID = (select cal.ORG_ID from CALENDAR.CA_CALENDAR cal where cal.CALENDAR_UUID = CALENDAR.CA_MEMBERSHIP.CALENDAR_UUID);
commit;

delete from CALENDAR.CA_EVENT where not exists (select 1 from CALENDAR.CA_CALENDAR cal where cal.CALENDAR_UUID = CALENDAR.CA_EVENT.CALENDAR_UUID);
update CALENDAR.CA_EVENT set ORG_ID = (select cal.ORG_ID from CALENDAR.CA_CALENDAR cal where cal.CALENDAR_UUID = CALENDAR.CA_EVENT.CALENDAR_UUID);
commit;

delete from CALENDAR.CA_EVENTINSTANCE where not exists (select 1 from CALENDAR.CA_CALENDAR cal where cal.CALENDAR_UUID = CALENDAR.CA_EVENTINSTANCE.CALENDAR_UUID);
update CALENDAR.CA_EVENTINSTANCE set ORG_ID = (select cal.ORG_ID from CALENDAR.CA_CALENDAR cal where cal.CALENDAR_UUID = CALENDAR.CA_EVENTINSTANCE.CALENDAR_UUID);
commit;

delete from CALENDAR.CA_SUBSTITUTION where not exists (select 1 from CALENDAR.CA_CALENDAR cal where cal.CALENDAR_UUID = CALENDAR.CA_SUBSTITUTION.CALENDAR_UUID);
update CALENDAR.CA_SUBSTITUTION set ORG_ID = (select cal.ORG_ID from CALENDAR.CA_CALENDAR cal where cal.CALENDAR_UUID = CALENDAR.CA_SUBSTITUTION.CALENDAR_UUID);
commit;

delete from CALENDAR.CA_RECURRENCE where not exists (select 1 from CALENDAR.CA_CALENDAR cal where cal.CALENDAR_UUID = CALENDAR.CA_RECURRENCE.CALENDAR_UUID);
update CALENDAR.CA_RECURRENCE set ORG_ID = (select cal.ORG_ID from CALENDAR.CA_CALENDAR cal where cal.CALENDAR_UUID = CALENDAR.CA_RECURRENCE.CALENDAR_UUID);
commit;

delete from CALENDAR.CA_EVENTINFO where not exists (select 1 from CALENDAR.CA_CALENDAR cal where cal.CALENDAR_UUID = CALENDAR.CA_EVENTINFO.CALENDAR_UUID);
update CALENDAR.CA_EVENTINFO set ORG_ID = (select cal.ORG_ID from CALENDAR.CA_CALENDAR cal where cal.CALENDAR_UUID = CALENDAR.CA_EVENTINFO.CALENDAR_UUID);
commit;

delete from CALENDAR.CA_EVENTTAG where not exists (select 1 from CALENDAR.CA_CALENDAR cal where cal.CALENDAR_UUID = CALENDAR.CA_EVENTTAG.CALENDAR_UUID);
update CALENDAR.CA_EVENTTAG set ORG_ID = (select cal.ORG_ID from CALENDAR.CA_CALENDAR cal where cal.CALENDAR_UUID = CALENDAR.CA_EVENTTAG.CALENDAR_UUID);
commit;

delete from CALENDAR.CA_EVENTCOMMENT where not exists (select 1 from CALENDAR.CA_CALENDAR cal where cal.CALENDAR_UUID = CALENDAR.CA_EVENTCOMMENT.CALENDAR_UUID);
update CALENDAR.CA_EVENTCOMMENT set ORG_ID = (select cal.ORG_ID from CALENDAR.CA_CALENDAR cal where cal.CALENDAR_UUID = CALENDAR.CA_EVENTCOMMENT.CALENDAR_UUID);
commit;

delete from CALENDAR.CA_EVENTFOLLOWING where not exists (select 1 from CALENDAR.CA_CALENDAR cal where cal.CALENDAR_UUID = CALENDAR.CA_EVENTFOLLOWING.CALENDAR_UUID);
update CALENDAR.CA_EVENTFOLLOWING set ORG_ID = (select cal.ORG_ID from CALENDAR.CA_CALENDAR cal where cal.CALENDAR_UUID = CALENDAR.CA_EVENTFOLLOWING.CALENDAR_UUID);
commit;

-- drop primary key for all tables
alter table CALENDAR.CA_MEMBERSHIP drop primary key drop index;
alter table CALENDAR.CA_CALENDAR drop primary key drop index;
alter table CALENDAR.CA_RECURRENCE drop primary key drop index;
alter table CALENDAR.CA_EVENT drop primary key drop index;
alter table CALENDAR.CA_EVENTINSTANCE drop primary key drop index;
alter table CALENDAR.CA_SUBSTITUTION drop primary key drop index;
alter table CALENDAR.CA_EVENTINFO drop primary key drop index;
alter table CALENDAR.CA_EVENTTAG drop primary key drop index;
alter table CALENDAR.CA_EVENTTAGAGG drop primary key drop index;
alter table CALENDAR.CA_EVENTCOMMENT drop primary key drop index;
alter table CALENDAR.CA_EVENTFOLLOWING drop primary key drop index;
alter table CALENDAR.CA_DELETION_HISTORY drop primary key drop index;
commit;

-- drop index
DECLARE
  COUNT_INDEXES INTEGER;
BEGIN
  SELECT COUNT(*) INTO COUNT_INDEXES
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'CALENDAR.CA_CAL_VISIBILITY_IDX';

  IF COUNT_INDEXES > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX CALENDAR.CA_CAL_VISIBILITY_IDX';
  END IF;
END;
/

drop index CALENDAR.CA_CAL_ACLMODTIME_IDX;
drop index CALENDAR.CA_EV_CALID_IDX;
drop index CALENDAR.CA_EV_USERID_IDX;
drop index CALENDAR.CA_EV_CALID_USERID_IDX;
drop index CALENDAR.CA_EV_MODITIME_IDX;
drop index CALENDAR.CA_EV_DBMODTIME_IDX;
drop index CALENDAR.CA_EVINST_CALID_EDSD_IDX;
drop index CALENDAR.CA_EVINST_CALID_EVID_IDX;
drop index CALENDAR.CA_EVINST_EVID_SD_IDX;
drop index CALENDAR.CA_EVINST_EVID_EDSD_IDX;
drop index CALENDAR.CA_EVINST_INST_EDSD_IDX;
drop index CALENDAR.CA_SUB_CALID_IDX;
drop index CALENDAR.CA_SUB_EVID_NSD_IDX;
drop index CALENDAR.CA_SUB_EVID_SD_IDX;
drop index CALENDAR.CA_SUB_MODITIME_IDX;
drop index CALENDAR.CA_RECUR_CALID_IDX;
drop index CALENDAR.CA_RECUR_MODITIME_IDX;
drop index CALENDAR.CA_EVINFO_CALID_IDX;
drop index CALENDAR.CA_EVINFO_EVID_IDX;
drop index CALENDAR.CA_EVTAG_EVID_IDX;
drop index CALENDAR.CA_EVTAG_CALID_IDX;
drop index CALENDAR.CA_EVTAG_NAME_IDX;
drop index CALENDAR.CA_EVTAG_NAME_EVID_IDX;
drop index CALENDAR.CA_EVTAGAGG_CALID_IDX;
drop index CALENDAR.CA_EVTAGAGG_CALID_NAME_IDX;
drop index CALENDAR.CA_EVCMT_EVID_IDX;
drop index CALENDAR.CA_EVFLW_CAID_IDX;
drop index CALENDAR.CA_EVFLW_EVID_IDX;
drop index CALENDAR.CA_EVFLW_EVITEM_IDX;
drop index CALENDAR.CA_EVFLW_USR_IDX;
drop index CALENDAR.CA_DELHIS_TIME_IDX;
commit;

-- recreate index
CREATE INDEX CALENDAR.CA_CAL_ACLMODTIME_IDX ON CALENDAR.CA_CALENDAR(ACLMODTIME, CREATEDON, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_CAL_VISIBILITY_IDX ON CALENDAR.CA_CALENDAR(CALENDAR_UUID, VISIBILITY, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EV_CALID_IDX ON CALENDAR.CA_EVENT(CALENDAR_UUID, CREATEDON DESC, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EV_USERID_IDX ON CALENDAR.CA_EVENT(CREATEDBY, CREATEDON DESC, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EV_CALID_USERID_IDX ON CALENDAR.CA_EVENT(CALENDAR_UUID, CREATEDBY, CREATEDON DESC, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EV_MODITIME_IDX ON CALENDAR.CA_EVENT(MODIFIEDON, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EV_DBMODTIME_IDX ON CALENDAR.CA_EVENT(DBMODTIME, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVINST_CALID_EDSD_IDX ON CALENDAR.CA_EVENTINSTANCE(CALENDAR_UUID, ENDDATE, STARTDATE, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVINST_CALID_EVID_IDX ON CALENDAR.CA_EVENTINSTANCE(CALENDAR_UUID, EVENT_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVINST_EVID_SD_IDX ON CALENDAR.CA_EVENTINSTANCE(EVENT_UUID, STARTDATE, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVINST_EVID_EDSD_IDX ON CALENDAR.CA_EVENTINSTANCE(EVENT_UUID, ENDDATE DESC, STARTDATE, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE UNIQUE INDEX CALENDAR.CA_EVINST_INST_EDSD_IDX ON CALENDAR.CA_EVENTINSTANCE(EVENTINST_UUID, ENDDATE, STARTDATE, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_SUB_CALID_IDX ON CALENDAR.CA_SUBSTITUTION(CALENDAR_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_SUB_EVID_NSD_IDX ON CALENDAR.CA_SUBSTITUTION(EVENT_UUID, NEWSTARTDATE, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_SUB_EVID_SD_IDX ON CALENDAR.CA_SUBSTITUTION(EVENT_UUID, STARTDATE, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_SUB_MODITIME_IDX ON CALENDAR.CA_SUBSTITUTION(MODIFIEDON, EVENTINFO_UUID, ISCANCELLED, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_RECUR_CALID_IDX ON CALENDAR.CA_RECURRENCE(CALENDAR_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_RECUR_MODITIME_IDX ON CALENDAR.CA_RECURRENCE(MODIFIEDON, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVINFO_CALID_IDX ON CALENDAR.CA_EVENTINFO(CALENDAR_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVINFO_EVID_IDX ON CALENDAR.CA_EVENTINFO(EVENT_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVTAG_EVID_IDX ON CALENDAR.CA_EVENTTAG(EVENT_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVTAG_CALID_IDX ON CALENDAR.CA_EVENTTAG(CALENDAR_UUID, NAME, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVTAG_NAME_IDX ON CALENDAR.CA_EVENTTAG(NAME, CALENDAR_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE UNIQUE INDEX CALENDAR.CA_EVTAG_NAME_EVID_IDX ON CALENDAR.CA_EVENTTAG(NAME, EVENT_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVTAGAGG_CALID_IDX ON CALENDAR.CA_EVENTTAGAGG(CALENDAR_UUID, TOTAL, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE UNIQUE INDEX CALENDAR.CA_EVTAGAGG_CALID_NAME_IDX ON CALENDAR.CA_EVENTTAGAGG(CALENDAR_UUID, NAME, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVCMT_EVID_IDX ON CALENDAR.CA_EVENTCOMMENT(EVENT_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVFLW_CAID_IDX ON CALENDAR.CA_EVENTFOLLOWING(CALENDAR_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVFLW_EVID_IDX ON CALENDAR.CA_EVENTFOLLOWING(EVENT_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE UNIQUE INDEX CALENDAR.CA_EVFLW_EVITEM_IDX ON CALENDAR.CA_EVENTFOLLOWING(EVENTITEM_UUID, EVENTITEM_TYPE, USER_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVFLW_USR_IDX ON CALENDAR.CA_EVENTFOLLOWING(USER_UUID, ENDDATE, FOLLOW, CALENDAR_UUID, EVENTITEM_UUID, EVENTITEM_TYPE, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_DELHIS_TIME_IDX ON CALENDAR.CA_DELETION_HISTORY(DBMODTIME, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
commit;

-- recreate primary keys
ALTER TABLE CALENDAR.CA_MEMBERSHIP
	ADD (CONSTRAINT CA_MEMBERSHIP_PK PRIMARY KEY (MEMBER_UUID, CALENDAR_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);

ALTER TABLE CALENDAR.CA_CALENDAR
	ADD (CONSTRAINT CA_CALENDAR_PK PRIMARY KEY (CALENDAR_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);
	
ALTER TABLE CALENDAR.CA_RECURRENCE
    ADD (CONSTRAINT CA_RECURRENCE_PK PRIMARY KEY (EVENT_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);

ALTER TABLE CALENDAR.CA_EVENT
    ADD (CONSTRAINT CA_EVENT_PK PRIMARY KEY (EVENT_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);

ALTER TABLE CALENDAR.CA_EVENTINSTANCE
    ADD (CONSTRAINT CA_EVENTINST_PK PRIMARY KEY (EVENTINST_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);

ALTER TABLE CALENDAR.CA_SUBSTITUTION
    ADD (CONSTRAINT CA_SUBSTITUTION_PK PRIMARY KEY (SUBSTITUTION_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);

ALTER TABLE CALENDAR.CA_EVENTINFO
    ADD (CONSTRAINT CA_EVENTINFO_PK PRIMARY KEY (EVENTINFO_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);
	
ALTER TABLE CALENDAR.CA_EVENTTAG 
	ADD (CONSTRAINT CA_EVTAG_PK PRIMARY KEY (TAG_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);
	
ALTER TABLE CALENDAR.CA_EVENTTAGAGG 
	ADD (CONSTRAINT CA_EVTAGAGG_PK PRIMARY KEY (TAGAGG_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);

ALTER TABLE CALENDAR.CA_EVENTCOMMENT 
	ADD (CONSTRAINT CA_EVCMT_PK PRIMARY KEY (COMMENT_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);
	
ALTER TABLE CALENDAR.CA_EVENTFOLLOWING
	ADD (CONSTRAINT CA_EVFLW_PK PRIMARY KEY (EVFLW_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);
	
ALTER TABLE CALENDAR.CA_DELETION_HISTORY
	ADD (CONSTRAINT CA_DELHISTORY_PK PRIMARY KEY (DELHISTORY_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);

commit;

-- drop ORG_ID column default value
alter table CALENDAR.CA_MEMBERSHIP modify ORG_ID default null;
alter table CALENDAR.CA_EVENT modify ORG_ID default null;
alter table CALENDAR.CA_EVENTINSTANCE modify ORG_ID default null;
alter table CALENDAR.CA_SUBSTITUTION modify ORG_ID default null;
alter table CALENDAR.CA_RECURRENCE modify ORG_ID default null;
alter table CALENDAR.CA_EVENTINFO modify ORG_ID default null;
alter table CALENDAR.CA_EVENTTAG modify ORG_ID default null;
alter table CALENDAR.CA_EVENTTAGAGG modify ORG_ID default null;
alter table CALENDAR.CA_EVENTCOMMENT modify ORG_ID default null;
alter table CALENDAR.CA_EVENTFOLLOWING modify ORG_ID default null;
commit;

UPDATE CALENDAR.CA_SCHEMA SET DBSCHEMAVER = '25', RELEASEVER = '4.5.0.0.0' WHERE COMPKEY = 'CALENDAR';
commit;

QUIT;