-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2011, 2014                      
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

UPDATE CALENDAR.CA_SCHEMA SET DBSCHEMAVER = '2', RELEASEVER = '4.0.0.0.0' WHERE COMPKEY = 'CALENDAR';

ALTER TABLE CALENDAR.CA_CALENDAR ADD (CREATEDON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL); 
ALTER TABLE CALENDAR.CA_CALENDAR ADD (ACLMODTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL); 
ALTER TABLE CALENDAR.CA_SUBSTITUTION ADD (MODIFIEDON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL); 
ALTER TABLE CALENDAR.CA_RECURRENCE ADD (MODIFIEDON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL); 

CREATE INDEX CALENDAR.CA_CAL_ACLMODTIME_IDX ON CALENDAR.CA_CALENDAR(ACLMODTIME, CREATEDON)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EV_MODITIME_IDX ON CALENDAR.CA_EVENT(MODIFIEDON)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_SUB_MODITIME_IDX ON CALENDAR.CA_SUBSTITUTION(MODIFIEDON, EVENTINFO_UUID, ISCANCELLED)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_RECUR_MODITIME_IDX ON CALENDAR.CA_RECURRENCE(MODIFIEDON)TABLESPACE CALENDARINDEXTABSPACE;

CREATE TABLE CALENDAR.CA_DELETION_HISTORY (
	DELHISTORY_UUID	VARCHAR(36)	NOT NULL,	
	OBJECT_TYPE		INTEGER 	NOT NULL, -- 0 - EVENT, 1 - EXCEPTION INSTANCE
	OBJECT_UUID		VARCHAR(36) NOT NULL,
	DBMODTIME		TIMESTAMP	NOT NULL
)TABLESPACE CALENDARREGTABSPACE;
CREATE INDEX CALENDAR.CA_DELHIS_TIME_IDX ON CALENDAR.CA_DELETION_HISTORY(DBMODTIME)TABLESPACE CALENDARINDEXTABSPACE;

ALTER TABLE CALENDAR.CA_DELETION_HISTORY
	ADD (CONSTRAINT CA_DELHISTORY_PK PRIMARY KEY (DELHISTORY_UUID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);
	
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_DELETION_HISTORY TO SNCOMMUSER_ROLE;

COMMIT;

QUIT;