-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2011                              
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

CONNECT TO SNCOMM@

UPDATE CALENDAR.CA_SCHEMA SET DBSCHEMAVER = '10', RELEASEVER = '4.0.0.0.0' WHERE COMPKEY = 'CALENDAR'@

ALTER TABLE CALENDAR.CA_CALENDAR ADD COLUMN CREATEDON TIMESTAMP NOT NULL WITH DEFAULT CURRENT_TIMESTAMP@
ALTER TABLE CALENDAR.CA_CALENDAR ADD COLUMN ACLMODTIME TIMESTAMP NOT NULL WITH DEFAULT CURRENT_TIMESTAMP@
ALTER TABLE CALENDAR.CA_SUBSTITUTION ADD COLUMN MODIFIEDON TIMESTAMP NOT NULL WITH DEFAULT CURRENT_TIMESTAMP@
ALTER TABLE CALENDAR.CA_RECURRENCE ADD COLUMN MODIFIEDON TIMESTAMP NOT NULL WITH DEFAULT CURRENT_TIMESTAMP@

CREATE INDEX CALENDAR.CA_CAL_ACLMODTIME_IDX ON CALENDAR.CA_CALENDAR(ACLMODTIME, CREATEDON)@
CREATE INDEX CALENDAR.CA_EV_MODITIME_IDX ON CALENDAR.CA_EVENT(MODIFIEDON)@
CREATE INDEX CALENDAR.CA_SUB_MODITIME_IDX ON CALENDAR.CA_SUBSTITUTION(MODIFIEDON, EVENTINFO_UUID, ISCANCELLED)@
CREATE INDEX CALENDAR.CA_RECUR_MODITIME_IDX ON CALENDAR.CA_RECURRENCE(MODIFIEDON)@

CREATE TABLE CALENDAR.CA_DELETION_HISTORY (
	DELHISTORY_UUID	VARCHAR(36)	NOT NULL,	
	OBJECT_TYPE		SMALLINT 	NOT NULL, -- 0 - EVENT, 1 - EXCEPTION INSTANCE
	OBJECT_UUID		VARCHAR(36) NOT NULL,
	DBMODTIME		TIMESTAMP	NOT NULL
	)
IN CALENDARTABSPACE@
CREATE INDEX CALENDAR.CA_DELHIS_TIME_IDX ON CALENDAR.CA_DELETION_HISTORY(DBMODTIME)@

ALTER TABLE CALENDAR.CA_DELETION_HISTORY
ADD CONSTRAINT CA_DELHISTORY_PK PRIMARY KEY (
	DELHISTORY_UUID
)@

GRANT INSERT, DELETE, UPDATE, SELECT ON TABLE CALENDAR.CA_DELETION_HISTORY TO USER LCUSER@

-- 20110711, fixup03
ALTER TABLE CALENDAR.CA_CALENDAR ADD COLUMN WIDGETID VARCHAR(48)@

-- 20110711, fixup04
CREATE TABLE CALENDAR.CA_EVENTTAG (
	TAG_UUID		VARCHAR(36)	 NOT NULL,
	CALENDAR_UUID	VARCHAR(36)	 NOT NULL,
	EVENT_UUID		VARCHAR(36)	 NOT NULL,
	NAME	    	VARCHAR(256) NOT NULL,
	MODIFIEDON	    TIMESTAMP	 NOT NULL
	)
IN CALENDARTABSPACE@
CREATE INDEX CALENDAR.CA_EVTAG_EVID_IDX ON CALENDAR.CA_EVENTTAG(EVENT_UUID)@
CREATE INDEX CALENDAR.CA_EVTAG_CALID_IDX ON CALENDAR.CA_EVENTTAG(CALENDAR_UUID, NAME)@
CREATE INDEX CALENDAR.CA_EVTAG_NAME_IDX ON CALENDAR.CA_EVENTTAG(NAME, CALENDAR_UUID)@
CREATE UNIQUE INDEX CALENDAR.CA_EVTAG_NAME_EVID_IDX ON CALENDAR.CA_EVENTTAG(NAME, EVENT_UUID)@

CREATE TABLE CALENDAR.CA_EVENTTAGAGG (
	TAGAGG_UUID		VARCHAR(36)	 NOT NULL,
	CALENDAR_UUID	VARCHAR(36),
	NAME	    	VARCHAR(256) NOT NULL,
	TOTAL			INTEGER		 NOT NULL,
	LASTUSED	    TIMESTAMP	 NOT NULL
	)
IN CALENDARTABSPACE@
CREATE INDEX CALENDAR.CA_EVTAGAGG_CALID_IDX ON CALENDAR.CA_EVENTTAGAGG(CALENDAR_UUID, TOTAL)@
CREATE UNIQUE INDEX CALENDAR.CA_EVTAGAGG_CALID_NAME_IDX ON CALENDAR.CA_EVENTTAGAGG(CALENDAR_UUID, NAME)@

CREATE TABLE CALENDAR.CA_EVENTCOMMENT (
	COMMENT_UUID	VARCHAR(36)	 NOT NULL,
	CALENDAR_UUID	VARCHAR(36)	 NOT NULL,
	EVENT_UUID		VARCHAR(36)	 NOT NULL,
	CREATEDBY		VARCHAR(36)	 NOT NULL,
	CREATEON		TIMESTAMP	 NOT NULL,
	CONTENT	    	CLOB(102400) NOT NULL
	)
IN CALENDARTABSPACE@
CREATE INDEX CALENDAR.CA_EVCMT_EVID_IDX ON CALENDAR.CA_EVENTCOMMENT(EVENT_UUID)@

ALTER TABLE CALENDAR.CA_EVENTTAG
ADD CONSTRAINT CA_EVTAG_PK PRIMARY KEY (
	TAG_UUID
)@

ALTER TABLE CALENDAR.CA_EVENTTAGAGG
ADD CONSTRAINT CA_EVTAGAGG_PK PRIMARY KEY (
	TAGAGG_UUID
)@

ALTER TABLE CALENDAR.CA_EVENTCOMMENT
ADD CONSTRAINT CA_EVCMT_PK PRIMARY KEY (
	COMMENT_UUID
)@

GRANT INSERT, DELETE, UPDATE, SELECT ON TABLE CALENDAR.CA_EVENTTAG TO USER LCUSER@
GRANT INSERT, DELETE, UPDATE, SELECT ON TABLE CALENDAR.CA_EVENTTAGAGG TO USER LCUSER@
GRANT INSERT, DELETE, UPDATE, SELECT ON TABLE CALENDAR.CA_EVENTCOMMENT TO USER LCUSER@

-- 20110721, fixup05
ALTER TABLE CALENDAR.CA_EVENT ADD COLUMN DBMODTIME TIMESTAMP@
CREATE INDEX CALENDAR.CA_EV_DBMODTIME_IDX ON CALENDAR.CA_EVENT(DBMODTIME)@

-- 20110802, fixup06
ALTER TABLE CALENDAR.CA_EVENTINSTANCE ADD COLUMN MODIFIEDBY VARCHAR(36)@
ALTER TABLE CALENDAR.CA_EVENTINSTANCE ADD COLUMN MODIFIEDON TIMESTAMP@

-- 20110817, fixup07
ALTER TABLE CALENDAR.CA_EVENTINFO ADD COLUMN IMAGE_URL VARCHAR(1024)@

-- 20110821, fixup08
CREATE INDEX CALENDAR.CA_CAL_VISIBILITY_IDX ON CALENDAR.CA_CALENDAR(CALENDAR_UUID, VISIBILITY)@

DROP INDEX CALENDAR.CA_EV_CALID_IDX@
CREATE INDEX CALENDAR.CA_EV_CALID_IDX ON CALENDAR.CA_EVENT(CALENDAR_UUID, CREATEDON DESC)@
CREATE INDEX CALENDAR.CA_EV_USERID_IDX ON CALENDAR.CA_EVENT(CREATEDBY, CREATEDON DESC)@
CREATE INDEX CALENDAR.CA_EV_CALID_USERID_IDX ON CALENDAR.CA_EVENT(CALENDAR_UUID, CREATEDBY, CREATEDON DESC)@

-- 20110921, fixup09
DROP INDEX CALENDAR.CA_EVINST_CALID_SD_IDX@

CREATE INDEX CALENDAR.CA_EVINST_CALID_EDSD_IDX ON CALENDAR.CA_EVENTINSTANCE(CALENDAR_UUID, ENDDATE, STARTDATE) CLUSTER@
CREATE INDEX CALENDAR.CA_EVINST_EVID_EDSD_IDX ON CALENDAR.CA_EVENTINSTANCE(EVENT_UUID, ENDDATE DESC, STARTDATE)@
CREATE UNIQUE INDEX CALENDAR.CA_EVINST_INST_EDSD_IDX ON CALENDAR.CA_EVENTINSTANCE(EVENTINST_UUID, ENDDATE, STARTDATE)@

CREATE TABLE CALENDAR.CA_EVENTFOLLOWING (
    EVFLW_UUID		VARCHAR(36)	 NOT NULL,
    CALENDAR_UUID	VARCHAR(36)	 NOT NULL,
    EVENT_UUID		VARCHAR(36)	 NOT NULL,
    EVENTITEM_UUID  VARCHAR(36)  NOT NULL,
    EVENTITEM_TYPE	SMALLINT	 NOT NULL, -- 0: event, 1: instance
    ENDDATE			TIMESTAMP	 NOT NULL,
    USER_UUID		VARCHAR(36)	 NOT NULL,
    FOLLOW   		SMALLINT	 NOT NULL, -- event 'follow' type, 0x01: follow, 0x02: attend, 0x10: both attend and follow
    MODIFIEDON		TIMESTAMP	 NOT NULL
)
IN CALENDARTABSPACE@
CREATE INDEX CALENDAR.CA_EVFLW_CAID_IDX ON CALENDAR.CA_EVENTFOLLOWING(CALENDAR_UUID)@
CREATE INDEX CALENDAR.CA_EVFLW_EVID_IDX ON CALENDAR.CA_EVENTFOLLOWING(EVENT_UUID)@
CREATE UNIQUE INDEX CALENDAR.CA_EVFLW_EVITEM_IDX ON CALENDAR.CA_EVENTFOLLOWING(EVENTITEM_UUID, EVENTITEM_TYPE, USER_UUID)@
CREATE UNIQUE INDEX CALENDAR.CA_EVFLW_USR_IDX ON CALENDAR.CA_EVENTFOLLOWING(USER_UUID, ENDDATE, EVFLW_UUID) INCLUDE (FOLLOW, CALENDAR_UUID, EVENTITEM_UUID, EVENTITEM_TYPE)@

CREATE TABLE CALENDAR.CA_MISCDATA (
    NAME          	VARCHAR(256)  NOT NULL,
    VAL       		VARCHAR(1024) NOT NULL,
    MODIFIEDON		TIMESTAMP	  NOT NULL
)
IN CALENDARTABSPACE@

ALTER TABLE CALENDAR.CA_EVENTFOLLOWING
ADD CONSTRAINT CA_EVFLW_PK PRIMARY KEY (
	EVFLW_UUID
)@

ALTER TABLE CALENDAR.CA_MISCDATA
ADD CONSTRAINT CA_MISCDATA_PK PRIMARY KEY (
	NAME
)@

GRANT INSERT, DELETE, UPDATE, SELECT ON TABLE CALENDAR.CA_EVENTFOLLOWING TO USER LCUSER@
GRANT INSERT, DELETE, UPDATE, SELECT ON TABLE CALENDAR.CA_MISCDATA TO USER LCUSER@

COMMIT@

CONNECT RESET@
