-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2011, 2014                            
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 
                                                        
CONNECT TO SNCOMM@

RUNSTATS ON TABLE CALENDAR.CA_SCHEMA WITH DISTRIBUTION@
RUNSTATS ON TABLE CALENDAR.CA_MEMBERSHIP WITH DISTRIBUTION@
RUNSTATS ON TABLE CALENDAR.CA_EVENT WITH DISTRIBUTION@
RUNSTATS ON TABLE CALENDAR.CA_EVENTINFO WITH DISTRIBUTION@
RUNSTATS ON TABLE CALENDAR.CA_RECURRENCE WITH DISTRIBUTION@
RUNSTATS ON TABLE CALENDAR.CA_EVENTINSTANCE WITH DISTRIBUTION@
RUNSTATS ON TABLE CALENDAR.CA_CALENDAR WITH DISTRIBUTION@
RUNSTATS ON TABLE CALENDAR.CA_SUBSTITUTION WITH DISTRIBUTION@
RUNSTATS ON TABLE CALENDAR.CA_DELETION_HISTORY WITH DISTRIBUTION@
RUNSTATS ON TABLE CALENDAR.CA_EVENTTAG WITH DISTRIBUTION@
RUNSTATS ON TABLE CALENDAR.CA_EVENTTAGAGG WITH DISTRIBUTION@
RUNSTATS ON TABLE CALENDAR.CA_EVENTCOMMENT WITH DISTRIBUTION@
RUNSTATS ON TABLE CALENDAR.CA_EVENTFOLLOWING WITH DISTRIBUTION@
RUNSTATS ON TABLE CALENDAR.CA_MISCDATA WITH DISTRIBUTION@
RUNSTATS ON TABLE CALENDAR.CA_USERMENTION WITH DISTRIBUTION@

RUNSTATS ON TABLE CALENDAR.CA_SCHEMA			FOR INDEXES ALL@
RUNSTATS ON TABLE CALENDAR.CA_MEMBERSHIP		FOR INDEXES ALL@
RUNSTATS ON TABLE CALENDAR.CA_EVENT				FOR INDEXES ALL@
RUNSTATS ON TABLE CALENDAR.CA_EVENTINFO			FOR INDEXES ALL@
RUNSTATS ON TABLE CALENDAR.CA_RECURRENCE		FOR INDEXES ALL@
RUNSTATS ON TABLE CALENDAR.CA_EVENTINSTANCE		FOR INDEXES ALL@
RUNSTATS ON TABLE CALENDAR.CA_CALENDAR			FOR INDEXES ALL@
RUNSTATS ON TABLE CALENDAR.CA_SUBSTITUTION		FOR INDEXES ALL@
RUNSTATS ON TABLE CALENDAR.CA_DELETION_HISTORY	FOR INDEXES ALL@
RUNSTATS ON TABLE CALENDAR.CA_EVENTTAG			FOR INDEXES ALL@
RUNSTATS ON TABLE CALENDAR.CA_EVENTTAGAGG		FOR INDEXES ALL@
RUNSTATS ON TABLE CALENDAR.CA_EVENTCOMMENT		FOR INDEXES ALL@
RUNSTATS ON TABLE CALENDAR.CA_EVENTFOLLOWING	FOR INDEXES ALL@
RUNSTATS ON TABLE CALENDAR.CA_MISCDATA			FOR INDEXES ALL@
RUNSTATS ON TABLE CALENDAR.CA_USERMENTION		FOR INDEXES ALL@

CONNECT RESET@
TERMINATE@
