-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2011, 2016                              
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

CONNECT TO SNCOMM@

CREATE BUFFERPOOL CA32KBP IMMEDIATE SIZE 8000 AUTOMATIC PAGESIZE 32K@
		
CREATE LARGE TABLESPACE CALENDARTABSPACE PAGESIZE 32K MANAGED BY DATABASE
	USING (FILE 'CALENDARTABSPACE' 25600)
	EXTENTSIZE 4
	PREFETCHSIZE AUTOMATIC
	BUFFERPOOL CA32KBP
	AUTORESIZE YES
	INCREASESIZE 20 M
	MAXSIZE NONE@

CREATE SYSTEM TEMPORARY TABLESPACE CATMPTABSPACE
	PAGESIZE 32K MANAGED BY SYSTEM 
	USING ( 'CATMPTABSPACE' ) 
	EXTENTSIZE 32 PREFETCHSIZE AUTOMATIC
	BUFFERPOOL CA32KBP@
	
--------------------------------------
-- CREATE THE SCHEMA
--------------------------------------

CREATE SCHEMA CALENDAR@  

--------------------------------------
-- CREATE THE TABLES
--------------------------------------

--------------------------------------
-- Schema info

CREATE TABLE CALENDAR.CA_SCHEMA (
	COMPKEY		VARCHAR(36)	NOT NULL,
    DBSCHEMAVER	VARCHAR(32)	NOT NULL,
	RELEASEVER  VARCHAR(32) NOT NULL WITH DEFAULT '',
	PRESCHEMAVER VARCHAR (10)  NOT NULL WITH DEFAULT '0',
	POSTSCHEMAVER VARCHAR (10)  NOT NULL WITH DEFAULT '0'
	)
IN CALENDARTABSPACE@

--------------------------------------
-- Calendar info

CREATE VIEW CALENDAR.CA_USER AS
   SELECT MEMBER_UUID AS MEMBER_UUID, DIRECTORY_UUID AS DIRECTORY_UUID, DISPLAY AS DISPLAY, EMAIL AS EMAIL, STATE AS STATE, ORG_ID AS ORG_ID, ISEXTERNAL AS ISEXTERNAL
   FROM SNCOMM.MEMBERPROFILE@
   
CREATE TABLE CALENDAR.CA_MEMBERSHIP(
	CALENDAR_UUID	VARCHAR(36)	    NOT NULL,
	MEMBER_UUID		VARCHAR(36)		NOT NULL,
	ROLE			SMALLINT		NOT NULL, -- 1: member, 2: owner
	ORG_ID          VARCHAR(36)     NOT NULL
	)
IN CALENDARTABSPACE@

CREATE TABLE CALENDAR.CA_CALENDAR (
	CALENDAR_UUID	VARCHAR(36)	    NOT NULL,
	COMMUNITY_UUID	VARCHAR(36)	    NOT NULL,
	COMMUNITY_NAME  VARCHAR(256)	NOT NULL,
	MEMBERS_ROLE    SMALLINT        NOT NULL WITH DEFAULT 1,
	VISIBILITY      SMALLINT        NOT NULL, -- 0: private, 1: public/moderated
	LAST_MODIFIED   TIMESTAMP		NOT NULL,
	CREATEDON		TIMESTAMP		NOT NULL WITH DEFAULT CURRENT_TIMESTAMP,
	ACLMODTIME		TIMESTAMP		NOT NULL WITH DEFAULT CURRENT_TIMESTAMP,
	WIDGETID		VARCHAR(48),
	ORG_ID          VARCHAR(36)     NOT NULL
	)
IN CALENDARTABSPACE@
CREATE INDEX CALENDAR.CA_CAL_ACLMODTIME_IDX ON CALENDAR.CA_CALENDAR(ACLMODTIME, CREATEDON, ORG_ID)@
CREATE INDEX CALENDAR.CA_CAL_VISIBILITY_IDX ON CALENDAR.CA_CALENDAR(CALENDAR_UUID, VISIBILITY, ORG_ID)@

CREATE TABLE CALENDAR.CA_EVENT (
	EVENT_UUID		VARCHAR(36)	NOT NULL,
	CALENDAR_UUID	VARCHAR(36)	NOT NULL,
	MODIFIEDBY		VARCHAR(36)	NOT NULL,
	CREATEDBY		VARCHAR(36)	NOT NULL,
	MODIFIEDON		TIMESTAMP	NOT NULL,
	CREATEDON		TIMESTAMP	NOT NULL,
	DFLTEVENTINFO	VARCHAR(36)	NOT NULL,
	ISRECURRENCE    SMALLINT	NOT NULL WITH DEFAULT 0,
	DBMODTIME 		TIMESTAMP,
	ORG_ID          VARCHAR(36) NOT NULL
	)
IN CALENDARTABSPACE@
CREATE INDEX CALENDAR.CA_EV_CALID_IDX ON CALENDAR.CA_EVENT(CALENDAR_UUID, CREATEDON DESC, ORG_ID)@
CREATE INDEX CALENDAR.CA_EV_USERID_IDX ON CALENDAR.CA_EVENT(CREATEDBY, CREATEDON DESC, ORG_ID)@
CREATE INDEX CALENDAR.CA_EV_CALID_USERID_IDX ON CALENDAR.CA_EVENT(CALENDAR_UUID, CREATEDBY, CREATEDON DESC, ORG_ID)@
CREATE INDEX CALENDAR.CA_EV_MODITIME_IDX ON CALENDAR.CA_EVENT(MODIFIEDON, ORG_ID)@
CREATE INDEX CALENDAR.CA_EV_DBMODTIME_IDX ON CALENDAR.CA_EVENT(DBMODTIME, ORG_ID)@

CREATE TABLE CALENDAR.CA_EVENTINSTANCE (
	EVENTINST_UUID  VARCHAR(36) NOT NULL,
	CALENDAR_UUID	VARCHAR(36)	NOT NULL,
	EVENT_UUID		VARCHAR(36)	NOT NULL,
	EVENTINFO_UUID	VARCHAR(36),
	STARTDATE		TIMESTAMP	NOT NULL,
	ENDDATE			TIMESTAMP	NOT NULL,
	MODIFIEDBY		VARCHAR(36),
	MODIFIEDON		TIMESTAMP,
	DBMODTIME		TIMESTAMP,
	ORG_ID          VARCHAR(36) NOT NULL
	)
IN CALENDARTABSPACE@
CREATE INDEX CALENDAR.CA_EVINST_CALID_EDSD_IDX ON CALENDAR.CA_EVENTINSTANCE(CALENDAR_UUID, ENDDATE, STARTDATE, ORG_ID) CLUSTER@
CREATE INDEX CALENDAR.CA_EVINST_CALID_EVID_IDX ON CALENDAR.CA_EVENTINSTANCE(CALENDAR_UUID, EVENT_UUID, ORG_ID)@
CREATE INDEX CALENDAR.CA_EVINST_EVID_SD_IDX ON CALENDAR.CA_EVENTINSTANCE(EVENT_UUID, STARTDATE, ORG_ID)@
CREATE INDEX CALENDAR.CA_EVINST_EVID_EDSD_IDX ON CALENDAR.CA_EVENTINSTANCE(EVENT_UUID, ENDDATE DESC, STARTDATE, ORG_ID)@
CREATE INDEX CALENDAR.CA_EVINST_ED_IDX ON CALENDAR.CA_EVENTINSTANCE(ENDDATE, ORG_ID)@
CREATE INDEX CALENDAR.CA_EVINST_DBMD_IDX ON CALENDAR.CA_EVENTINSTANCE(DBMODTIME, ORG_ID)@
CREATE UNIQUE INDEX CALENDAR.CA_EVINST_INST_EDSD_IDX ON CALENDAR.CA_EVENTINSTANCE(EVENTINST_UUID, ENDDATE, STARTDATE, ORG_ID)@

CREATE TABLE CALENDAR.CA_SUBSTITUTION (
	SUBSTITUTION_UUID	VARCHAR(36)	NOT NULL,
	CALENDAR_UUID		VARCHAR(36)	NOT NULL,
	EVENT_UUID			VARCHAR(36)	NOT NULL,
	STARTDATE			TIMESTAMP	NOT NULL,
	ISCANCELLED			SMALLINT	NOT NULL,
	EVENTINFO_UUID		VARCHAR(36),
	NEWSTARTDATE		TIMESTAMP,
	NEWENDDATE			TIMESTAMP,
	MODIFIEDON			TIMESTAMP	NOT NULL WITH DEFAULT CURRENT_TIMESTAMP,
	ORG_ID              VARCHAR(36) NOT NULL
	)
IN CALENDARTABSPACE@
CREATE INDEX CALENDAR.CA_SUB_CALID_IDX ON CALENDAR.CA_SUBSTITUTION(CALENDAR_UUID, ORG_ID)@
CREATE INDEX CALENDAR.CA_SUB_EVID_NSD_IDX ON CALENDAR.CA_SUBSTITUTION(EVENT_UUID, NEWSTARTDATE, ORG_ID)@
CREATE INDEX CALENDAR.CA_SUB_EVID_SD_IDX ON CALENDAR.CA_SUBSTITUTION(EVENT_UUID, STARTDATE, ORG_ID)@
CREATE INDEX CALENDAR.CA_SUB_MODITIME_IDX ON CALENDAR.CA_SUBSTITUTION(MODIFIEDON, EVENTINFO_UUID, ISCANCELLED, ORG_ID)@

CREATE TABLE CALENDAR.CA_RECURRENCE (
	EVENT_UUID		VARCHAR(36)	NOT NULL,
	CALENDAR_UUID	VARCHAR(36)	NOT NULL,
	FREQUENCYCODE	CHAR(1)		NOT NULL,
	INTERVAL		SMALLINT,
	UNTILRULE		TIMESTAMP,
	STARTDATE		TIMESTAMP	NOT NULL,
	ENDDATE			TIMESTAMP	NOT NULL,
	BYDAY			SMALLINT,
	MODIFIEDON		TIMESTAMP	NOT NULL WITH DEFAULT CURRENT_TIMESTAMP,
	ORG_ID          VARCHAR(36) NOT NULL
	)
IN CALENDARTABSPACE@
CREATE INDEX CALENDAR.CA_RECUR_CALID_IDX ON CALENDAR.CA_RECURRENCE(CALENDAR_UUID, ORG_ID)@
CREATE INDEX CALENDAR.CA_RECUR_MODITIME_IDX ON CALENDAR.CA_RECURRENCE(MODIFIEDON, ORG_ID)@

CREATE TABLE CALENDAR.CA_EVENTINFO (
	EVENTINFO_UUID	VARCHAR(36)	NOT NULL,
	CALENDAR_UUID	VARCHAR(36)	NOT NULL,
	EVENT_UUID		VARCHAR(36)	NOT NULL,
	DESCRIPTION	    CLOB(102400),
	LOCATION	    VARCHAR(256),
	NAME		    VARCHAR(256),
	ISALLDAY        SMALLINT,
	IMAGE_URL		VARCHAR(1024),
	ORG_ID          VARCHAR(36) NOT NULL
	)
IN CALENDARTABSPACE@
CREATE INDEX CALENDAR.CA_EVINFO_CALID_IDX ON CALENDAR.CA_EVENTINFO(CALENDAR_UUID, ORG_ID)@
CREATE INDEX CALENDAR.CA_EVINFO_EVID_IDX ON CALENDAR.CA_EVENTINFO(EVENT_UUID, ORG_ID)@

CREATE TABLE CALENDAR.CA_DELETION_HISTORY (
	DELHISTORY_UUID	VARCHAR(36)	NOT NULL,
	CALENDAR_UUID	VARCHAR(36)	NOT NULL DEFAULT '',
	OBJECT_TYPE		SMALLINT 	NOT NULL, -- 0 - EVENT, 1 - EXCEPTION INSTANCE
	OBJECT_UUID		VARCHAR(36) NOT NULL,
	DBMODTIME		TIMESTAMP	NOT NULL,
	ORG_ID          VARCHAR(36) NOT NULL
	)
IN CALENDARTABSPACE@
CREATE INDEX CALENDAR.CA_DELHIS_TIME_IDX ON CALENDAR.CA_DELETION_HISTORY(DBMODTIME, ORG_ID)@

-- tag

CREATE TABLE CALENDAR.CA_EVENTTAG (
	TAG_UUID		VARCHAR(36)	 NOT NULL,
	CALENDAR_UUID	VARCHAR(36)	 NOT NULL,
	EVENT_UUID		VARCHAR(36)	 NOT NULL,
	NAME	    	VARCHAR(256) NOT NULL,
	MODIFIEDON	    TIMESTAMP	 NOT NULL,
	ORG_ID          VARCHAR(36)  NOT NULL
	)
IN CALENDARTABSPACE@
CREATE INDEX CALENDAR.CA_EVTAG_EVID_IDX ON CALENDAR.CA_EVENTTAG(EVENT_UUID, ORG_ID)@
CREATE INDEX CALENDAR.CA_EVTAG_CALID_IDX ON CALENDAR.CA_EVENTTAG(CALENDAR_UUID, NAME, ORG_ID)@
CREATE INDEX CALENDAR.CA_EVTAG_NAME_IDX ON CALENDAR.CA_EVENTTAG(NAME, CALENDAR_UUID, ORG_ID)@
CREATE UNIQUE INDEX CALENDAR.CA_EVTAG_NAME_EVID_IDX ON CALENDAR.CA_EVENTTAG(NAME, EVENT_UUID, ORG_ID)@

CREATE TABLE CALENDAR.CA_EVENTTAGAGG (
	TAGAGG_UUID		VARCHAR(36)	 NOT NULL,
	CALENDAR_UUID	VARCHAR(36)  NOT NULL,
	NAME	    	VARCHAR(256) NOT NULL,
	TOTAL			INTEGER		 NOT NULL,
	LASTUSED	    TIMESTAMP	 NOT NULL,
	ORG_ID          VARCHAR(36)  NOT NULL
	)
IN CALENDARTABSPACE@
CREATE INDEX CALENDAR.CA_EVTAGAGG_CALID_IDX ON CALENDAR.CA_EVENTTAGAGG(CALENDAR_UUID, TOTAL, ORG_ID)@
CREATE UNIQUE INDEX CALENDAR.CA_EVTAGAGG_CALID_NAME_IDX ON CALENDAR.CA_EVENTTAGAGG(CALENDAR_UUID, NAME, ORG_ID)@

-- comment

CREATE TABLE CALENDAR.CA_EVENTCOMMENT (
	COMMENT_UUID	VARCHAR(36)	 NOT NULL,
	CALENDAR_UUID	VARCHAR(36)	 NOT NULL,
	EVENT_UUID		VARCHAR(36)	 NOT NULL,
	CREATEDBY		VARCHAR(36)	 NOT NULL,
	CREATEON		TIMESTAMP	 NOT NULL,
	CONTENT	    	CLOB(102400) NOT NULL,
	CONTENTTYPE     INTEGER      NOT NULL DEFAULT 2,
	ORG_ID          VARCHAR(36)  NOT NULL
	)
IN CALENDARTABSPACE@
CREATE INDEX CALENDAR.CA_EVCMT_EVID_IDX ON CALENDAR.CA_EVENTCOMMENT(EVENT_UUID, ORG_ID)@

-- following, rsvp, etc
CREATE TABLE CALENDAR.CA_EVENTFOLLOWING (
    EVFLW_UUID		VARCHAR(36)	 NOT NULL,
    CALENDAR_UUID	VARCHAR(36)	 NOT NULL,
    EVENT_UUID		VARCHAR(36)	 NOT NULL,
    EVENTITEM_UUID  VARCHAR(36)  NOT NULL,
    EVENTITEM_TYPE	SMALLINT	 NOT NULL, -- 0: event, 1: instance
    ENDDATE			TIMESTAMP	 NOT NULL,
    USER_UUID		VARCHAR(36)	 NOT NULL,
    FOLLOW   		SMALLINT	 NOT NULL, -- event 'follow' type, 0x01: follow, 0x02: attend, 0x10: both attend and follow
    MODIFIEDON		TIMESTAMP	 NOT NULL,
    ORG_ID          VARCHAR(36)  NOT NULL
)
IN CALENDARTABSPACE@
CREATE INDEX CALENDAR.CA_EVFLW_CAID_IDX ON CALENDAR.CA_EVENTFOLLOWING(CALENDAR_UUID, ORG_ID)@
CREATE INDEX CALENDAR.CA_EVFLW_EVID_IDX ON CALENDAR.CA_EVENTFOLLOWING(EVENT_UUID, ORG_ID)@
CREATE UNIQUE INDEX CALENDAR.CA_EVFLW_EVITEM_IDX ON CALENDAR.CA_EVENTFOLLOWING(EVENTITEM_UUID, EVENTITEM_TYPE, USER_UUID, ORG_ID)@
CREATE UNIQUE INDEX CALENDAR.CA_EVFLW_USR_IDX ON CALENDAR.CA_EVENTFOLLOWING(USER_UUID, ENDDATE, EVFLW_UUID, ORG_ID) INCLUDE (FOLLOW, CALENDAR_UUID, EVENTITEM_UUID, EVENTITEM_TYPE)@

CREATE TABLE CALENDAR.CA_MISCDATA (
    NAME          	VARCHAR(256)  NOT NULL,
    VAL       		VARCHAR(1024) NOT NULL,
    MODIFIEDON		TIMESTAMP	  NOT NULL
)
IN CALENDARTABSPACE@

CREATE TABLE CALENDAR.CA_USERMENTION (
    MENTION_UUID   VARCHAR(48) NOT NULL,
    OBJECT_ID      VARCHAR(48) NOT NULL,
    OBJECT_TYPE    INTEGER NOT NULL, -- 1: event, 2: instance, 3: comment
    CALENDAR_UUID  VARCHAR(48) NOT NULL,
    USER_UUID      VARCHAR(48) NOT NULL, 
    MENTIONEDBY    VARCHAR(48) NOT NULL, 
    CREATEDON      TIMESTAMP   NOT NULL,
    ORG_ID         VARCHAR(36) NOT NULL
)IN CALENDARTABSPACE@
CREATE INDEX CALENDAR.CA_UM_OBJECT_IDX on CALENDAR.CA_USERMENTION(OBJECT_ID, OBJECT_TYPE, ORG_ID)@
CREATE INDEX CALENDAR.CA_UM_USER_IDX on CALENDAR.CA_USERMENTION(USER_UUID, ORG_ID)@

--------------------------------------
-- PKs
--------------------------------------

ALTER TABLE CALENDAR.CA_MEMBERSHIP
ADD CONSTRAINT CA_MEMBERSHIP_PK PRIMARY KEY (
	MEMBER_UUID, CALENDAR_UUID, ORG_ID
)@

ALTER TABLE CALENDAR.CA_CALENDAR
ADD CONSTRAINT CA_CALENDAR_PK PRIMARY KEY (
	CALENDAR_UUID, ORG_ID
)@

ALTER TABLE CALENDAR.CA_RECURRENCE
ADD CONSTRAINT CA_RECURRENCE_PK PRIMARY KEY (
	EVENT_UUID, ORG_ID
)@

ALTER TABLE CALENDAR.CA_EVENT
ADD CONSTRAINT CA_EVENT_PK PRIMARY KEY (
	EVENT_UUID, ORG_ID
)@

ALTER TABLE CALENDAR.CA_EVENTINSTANCE
ADD CONSTRAINT CA_EVENTINST_PK PRIMARY KEY (
	EVENTINST_UUID, ORG_ID
)@

ALTER TABLE CALENDAR.CA_SUBSTITUTION
ADD CONSTRAINT CA_SUBSTITUTION_PK PRIMARY KEY (
	SUBSTITUTION_UUID, ORG_ID
)@

ALTER TABLE CALENDAR.CA_EVENTINFO
ADD CONSTRAINT CA_EVENTINFO_PK PRIMARY KEY (
	EVENTINFO_UUID, ORG_ID
)@

ALTER TABLE CALENDAR.CA_EVENTTAG
ADD CONSTRAINT CA_EVTAG_PK PRIMARY KEY (
	TAG_UUID, ORG_ID
)@

ALTER TABLE CALENDAR.CA_EVENTTAGAGG
ADD CONSTRAINT CA_EVTAGAGG_PK PRIMARY KEY (
	TAGAGG_UUID, ORG_ID
)@

ALTER TABLE CALENDAR.CA_EVENTCOMMENT
ADD CONSTRAINT CA_EVCMT_PK PRIMARY KEY (
	COMMENT_UUID, ORG_ID
)@

ALTER TABLE CALENDAR.CA_EVENTFOLLOWING
ADD CONSTRAINT CA_EVFLW_PK PRIMARY KEY (
	EVFLW_UUID, ORG_ID
)@

ALTER TABLE CALENDAR.CA_SCHEMA
ADD CONSTRAINT CA_SCHEMA_PK PRIMARY KEY (
	COMPKEY
)@

ALTER TABLE CALENDAR.CA_DELETION_HISTORY
ADD CONSTRAINT CA_DELHISTORY_PK PRIMARY KEY (
	DELHISTORY_UUID, ORG_ID
)@

ALTER TABLE CALENDAR.CA_MISCDATA
ADD CONSTRAINT CA_MISCDATA_PK PRIMARY KEY (
	NAME
)@

ALTER TABLE CALENDAR.CA_USERMENTION
ADD CONSTRAINT CA_USERMENTION_PK PRIMARY KEY (
	MENTION_UUID, ORG_ID
)@

--------------------------------------
-- INSERTS
--------------------------------------

INSERT INTO CALENDAR.CA_SCHEMA (COMPKEY, DBSCHEMAVER, RELEASEVER, POSTSCHEMAVER) VALUES ('CALENDAR', '40', '6.0.0.0.0', '40.0')@

--------------------------------------
-- COMMIT
--------------------------------------
COMMIT@

--------------------------------------
-- FLUSH
--------------------------------------
FLUSH PACKAGE CACHE DYNAMIC@


--------------------------------------
-- DISCONNECT
--------------------------------------
CONNECT RESET@
DISCONNECT ALL@
