-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2011, 2014                           
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 
                                                         
CONNECT TO SNCOMM@

REORG TABLE CALENDAR.CA_SCHEMA				USE CATMPTABSPACE@
REORG TABLE CALENDAR.CA_MEMBERSHIP			USE CATMPTABSPACE@
REORG TABLE CALENDAR.CA_EVENT				USE CATMPTABSPACE@
REORG TABLE CALENDAR.CA_EVENTINFO			USE CATMPTABSPACE@
REORG TABLE CALENDAR.CA_RECURRENCE			USE CATMPTABSPACE@
REORG TABLE CALENDAR.CA_EVENTINSTANCE		USE CATMPTABSPACE@
REORG TABLE CALENDAR.CA_CALENDAR			USE CATMPTABSPACE@
REORG TABLE CALENDAR.CA_SUBSTITUTION		USE CATMPTABSPACE@
REORG TABLE CALENDAR.CA_DELETION_HISTORY	USE CATMPTABSPACE@
REORG TABLE CALENDAR.CA_EVENTTAG			USE CATMPTABSPACE@
REORG TABLE CALENDAR.CA_EVENTTAGAGG			USE CATMPTABSPACE@
REORG TABLE CALENDAR.CA_EVENTCOMMENT		USE CATMPTABSPACE@
REORG TABLE CALENDAR.CA_EVENTFOLLOWING		USE CATMPTABSPACE@
REORG TABLE CALENDAR.CA_MISCDATA			USE CATMPTABSPACE@
REORG TABLE CALENDAR.CA_USERMENTION			USE CATMPTABSPACE@


REORG INDEXES ALL FOR TABLE CALENDAR.CA_SCHEMA@
REORG INDEXES ALL FOR TABLE CALENDAR.CA_MEMBERSHIP@
REORG INDEXES ALL FOR TABLE CALENDAR.CA_EVENT@ 
REORG INDEXES ALL FOR TABLE CALENDAR.CA_EVENTINFO@
REORG INDEXES ALL FOR TABLE CALENDAR.CA_RECURRENCE@
REORG INDEXES ALL FOR TABLE CALENDAR.CA_EVENTINSTANCE@
REORG INDEXES ALL FOR TABLE CALENDAR.CA_CALENDAR@
REORG INDEXES ALL FOR TABLE CALENDAR.CA_SUBSTITUTION@
REORG INDEXES ALL FOR TABLE CALENDAR.CA_DELETION_HISTORY@
REORG INDEXES ALL FOR TABLE CALENDAR.CA_EVENTTAG@
REORG INDEXES ALL FOR TABLE CALENDAR.CA_EVENTTAGAGG@
REORG INDEXES ALL FOR TABLE CALENDAR.CA_EVENTCOMMENT@
REORG INDEXES ALL FOR TABLE CALENDAR.CA_EVENTFOLLOWING@
REORG INDEXES ALL FOR TABLE CALENDAR.CA_MISCDATA@
REORG INDEXES ALL FOR TABLE CALENDAR.CA_USERMENTION@

CONNECT RESET@
TERMINATE@
