-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2011, 2016                            
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

CREATE SMALLFILE TABLESPACE "CALENDARREGTABSPACE" DATAFILE 'CALENDARREGTABSPACE' 
    SIZE 100M REUSE AUTOEXTEND ON NEXT 20M MAXSIZE UNLIMITED LOGGING 
    EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE SMALLFILE TABLESPACE "CALENDARINDEXTABSPACE" DATAFILE 'CALENDARINDEXTABSPACE' 
    SIZE 100M REUSE AUTOEXTEND ON NEXT 20M MAXSIZE UNLIMITED LOGGING 
    EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

COMMIT;

CREATE USER "CALENDAR" PROFILE "DEFAULT" IDENTIFIED BY "&1" DEFAULT TABLESPACE "CALENDARREGTABSPACE" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT CONNECT TO CALENDAR;
GRANT CREATE SYNONYM TO CALENDAR;
GRANT ALTER SESSION TO CALENDAR;
GRANT CREATE SESSION TO CALENDAR;
ALTER USER CALENDAR DEFAULT ROLE ALL;
GRANT ALTER TABLESPACE TO CALENDAR; 
GRANT UNLIMITED TABLESPACE TO CALENDAR; 

GRANT SELECT ON SNCOMM.MEMBERPROFILE TO CALENDAR;

COMMIT;

ALTER SESSION SET CURRENT_SCHEMA = CALENDAR;
-- Run this script to create the calendar database tables in your database.

-- *****************************************************
-- Create the tables and indices

CREATE TABLE CALENDAR.CA_SCHEMA (
	COMPKEY		VARCHAR(36)	NOT NULL,
    DBSCHEMAVER	VARCHAR(32)	NOT NULL,
	RELEASEVER  VARCHAR(32) NOT NULL,
	PRESCHEMAVER VARCHAR2 (10) DEFAULT '0' NOT NULL,
	POSTSCHEMAVER VARCHAR2 (10) DEFAULT '0' NOT NULL
)TABLESPACE CALENDARREGTABSPACE;

CREATE VIEW CALENDAR.CA_USER AS
   SELECT MEMBER_UUID AS MEMBER_UUID, DIRECTORY_UUID AS DIRECTORY_UUID, DISPLAY AS DISPLAY, EMAIL AS EMAIL, STATE AS STATE, ORG_ID AS ORG_ID, ISEXTERNAL AS ISEXTERNAL
   FROM SNCOMM.MEMBERPROFILE;
  
CREATE TABLE CALENDAR.CA_MEMBERSHIP(
	CALENDAR_UUID	VARCHAR(36)	    NOT NULL,
	MEMBER_UUID		VARCHAR(36)		NOT NULL,
	ROLE			INTEGER			NOT NULL, -- 1: member, 2: owner
	ORG_ID          VARCHAR(36)     NOT NULL
)TABLESPACE CALENDARREGTABSPACE;

CREATE TABLE CALENDAR.CA_CALENDAR (
	CALENDAR_UUID	VARCHAR(36)	    NOT NULL,
	COMMUNITY_UUID	VARCHAR(36)	    NOT NULL,
	COMMUNITY_NAME  VARCHAR(256)	NOT NULL,
	MEMBERS_ROLE    INTEGER         DEFAULT 1 NOT NULL,
	VISIBILITY      INTEGER         NOT NULL, -- 0: private, 1: public/moderated
	LAST_MODIFIED   TIMESTAMP		NOT NULL,
	CREATEDON		TIMESTAMP		DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ACLMODTIME		TIMESTAMP		DEFAULT CURRENT_TIMESTAMP NOT NULL,
	WIDGETID		VARCHAR(48),
	ORG_ID          VARCHAR(36)     NOT NULL
)TABLESPACE CALENDARREGTABSPACE;
CREATE INDEX CALENDAR.CA_CAL_ACLMODTIME_IDX ON CALENDAR.CA_CALENDAR(ACLMODTIME, CREATEDON, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_CAL_VISIBILITY_IDX ON CALENDAR.CA_CALENDAR(CALENDAR_UUID, VISIBILITY, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;

CREATE TABLE CALENDAR.CA_EVENT (
	EVENT_UUID		VARCHAR(36)	NOT NULL,
	CALENDAR_UUID	VARCHAR(36)	NOT NULL,
	MODIFIEDBY		VARCHAR(36)	NOT NULL,
	CREATEDBY		VARCHAR(36)	NOT NULL,
	MODIFIEDON		TIMESTAMP	NOT NULL,
	CREATEDON		TIMESTAMP	NOT NULL,
	DFLTEVENTINFO	VARCHAR(36)	NOT NULL,
	ISRECURRENCE    NUMBER(1)	DEFAULT 0 NOT NULL,
	DBMODTIME		TIMESTAMP,
	ORG_ID          VARCHAR(36) NOT NULL
)TABLESPACE CALENDARREGTABSPACE;
CREATE INDEX CALENDAR.CA_EV_CALID_IDX ON CALENDAR.CA_EVENT(CALENDAR_UUID, CREATEDON DESC, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EV_USERID_IDX ON CALENDAR.CA_EVENT(CREATEDBY, CREATEDON DESC, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EV_CALID_USERID_IDX ON CALENDAR.CA_EVENT(CALENDAR_UUID, CREATEDBY, CREATEDON DESC, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EV_MODITIME_IDX ON CALENDAR.CA_EVENT(MODIFIEDON, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EV_DBMODTIME_IDX ON CALENDAR.CA_EVENT(DBMODTIME, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;

CREATE TABLE CALENDAR.CA_EVENTINSTANCE (
	EVENTINST_UUID  VARCHAR(36) NOT NULL,
	CALENDAR_UUID	VARCHAR(36)	NOT NULL,
	EVENT_UUID		VARCHAR(36)	NOT NULL,
	EVENTINFO_UUID	VARCHAR(36),
	STARTDATE		TIMESTAMP	NOT NULL,
	ENDDATE			TIMESTAMP	NOT NULL,
	MODIFIEDBY		VARCHAR(36),
	MODIFIEDON		TIMESTAMP,
	DBMODTIME		TIMESTAMP,
	ORG_ID          VARCHAR(36) NOT NULL
)TABLESPACE CALENDARREGTABSPACE;
CREATE INDEX CALENDAR.CA_EVINST_CALID_EDSD_IDX ON CALENDAR.CA_EVENTINSTANCE(CALENDAR_UUID, ENDDATE, STARTDATE, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVINST_CALID_EVID_IDX ON CALENDAR.CA_EVENTINSTANCE(CALENDAR_UUID, EVENT_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVINST_EVID_SD_IDX ON CALENDAR.CA_EVENTINSTANCE(EVENT_UUID, STARTDATE, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVINST_EVID_EDSD_IDX ON CALENDAR.CA_EVENTINSTANCE(EVENT_UUID, ENDDATE DESC, STARTDATE, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVINST_ED_IDX ON CALENDAR.CA_EVENTINSTANCE(ENDDATE, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVINST_DBMD_IDX ON CALENDAR.CA_EVENTINSTANCE(DBMODTIME, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE UNIQUE INDEX CALENDAR.CA_EVINST_INST_EDSD_IDX ON CALENDAR.CA_EVENTINSTANCE(EVENTINST_UUID, ENDDATE, STARTDATE, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;

CREATE TABLE CALENDAR.CA_SUBSTITUTION (
	SUBSTITUTION_UUID	VARCHAR(36)	NOT NULL,
	CALENDAR_UUID		VARCHAR(36)	NOT NULL,
	EVENT_UUID			VARCHAR(36)	NOT NULL,
	STARTDATE			TIMESTAMP	NOT NULL,
	ISCANCELLED			NUMBER(1)	NOT NULL,
	EVENTINFO_UUID		VARCHAR(36),
	NEWSTARTDATE		TIMESTAMP,
	NEWENDDATE			TIMESTAMP,
	MODIFIEDON			TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ORG_ID              VARCHAR(36) NOT NULL
)TABLESPACE CALENDARREGTABSPACE;
CREATE INDEX CALENDAR.CA_SUB_CALID_IDX ON CALENDAR.CA_SUBSTITUTION(CALENDAR_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_SUB_EVID_NSD_IDX ON CALENDAR.CA_SUBSTITUTION(EVENT_UUID, NEWSTARTDATE, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_SUB_EVID_SD_IDX ON CALENDAR.CA_SUBSTITUTION(EVENT_UUID, STARTDATE, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_SUB_MODITIME_IDX ON CALENDAR.CA_SUBSTITUTION(MODIFIEDON, EVENTINFO_UUID, ISCANCELLED, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;

CREATE TABLE CALENDAR.CA_RECURRENCE (
	EVENT_UUID		VARCHAR(36)	NOT NULL,
	CALENDAR_UUID	VARCHAR(36)	NOT NULL,
	FREQUENCYCODE	CHAR(1)		NOT NULL,
	INTERVAL		INTEGER,
	UNTILRULE		TIMESTAMP,
	STARTDATE		TIMESTAMP	NOT NULL,
	ENDDATE			TIMESTAMP	NOT NULL,
	BYDAY			INTEGER,
	MODIFIEDON		TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ORG_ID          VARCHAR(36) NOT NULL
)TABLESPACE CALENDARREGTABSPACE;
CREATE INDEX CALENDAR.CA_RECUR_CALID_IDX ON CALENDAR.CA_RECURRENCE(CALENDAR_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_RECUR_MODITIME_IDX ON CALENDAR.CA_RECURRENCE(MODIFIEDON, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;

CREATE TABLE CALENDAR.CA_EVENTINFO (
	EVENTINFO_UUID	VARCHAR(36)	NOT NULL,
	CALENDAR_UUID	VARCHAR(36)	NOT NULL,
	EVENT_UUID		VARCHAR(36)	NOT NULL,
	DESCRIPTION	    CLOB,
	LOCATION	    VARCHAR(256),
	NAME		    VARCHAR(256),
	ISALLDAY        NUMBER(1),
	IMAGE_URL		VARCHAR(1024),
	ORG_ID          VARCHAR(36) NOT NULL
)TABLESPACE CALENDARREGTABSPACE;
CREATE INDEX CALENDAR.CA_EVINFO_CALID_IDX ON CALENDAR.CA_EVENTINFO(CALENDAR_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVINFO_EVID_IDX ON CALENDAR.CA_EVENTINFO(EVENT_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;

CREATE TABLE CALENDAR.CA_DELETION_HISTORY (
	DELHISTORY_UUID	VARCHAR(36)	NOT NULL,	
	CALENDAR_UUID	VARCHAR(36)	NOT NULL,
	OBJECT_TYPE		INTEGER 	NOT NULL, -- 0 - EVENT, 1 - EXCEPTION INSTANCE
	OBJECT_UUID		VARCHAR(36) NOT NULL,
	DBMODTIME		TIMESTAMP	NOT NULL,
	ORG_ID          VARCHAR(36) NOT NULL
)TABLESPACE CALENDARREGTABSPACE;
CREATE INDEX CALENDAR.CA_DELHIS_TIME_IDX ON CALENDAR.CA_DELETION_HISTORY(DBMODTIME, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;

CREATE TABLE CALENDAR.CA_EVENTTAG (
	TAG_UUID		VARCHAR(36)	 NOT NULL,
	CALENDAR_UUID	VARCHAR(36)	 NOT NULL,
	EVENT_UUID		VARCHAR(36)	 NOT NULL,
	NAME	    	VARCHAR(256) NOT NULL,
	MODIFIEDON	    TIMESTAMP	 NOT NULL,
	ORG_ID          VARCHAR(36)  NOT NULL
)TABLESPACE CALENDARREGTABSPACE;
CREATE INDEX CALENDAR.CA_EVTAG_EVID_IDX ON CALENDAR.CA_EVENTTAG(EVENT_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVTAG_CALID_IDX ON CALENDAR.CA_EVENTTAG(CALENDAR_UUID, NAME, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVTAG_NAME_IDX ON CALENDAR.CA_EVENTTAG(NAME, CALENDAR_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE UNIQUE INDEX CALENDAR.CA_EVTAG_NAME_EVID_IDX ON CALENDAR.CA_EVENTTAG(NAME, EVENT_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;

CREATE TABLE CALENDAR.CA_EVENTTAGAGG (
	TAGAGG_UUID		VARCHAR(36)	 NOT NULL,
	CALENDAR_UUID	VARCHAR(36)  NOT NULL,
	NAME	    	VARCHAR(256) NOT NULL,
	TOTAL			INTEGER		 NOT NULL,
	LASTUSED	    TIMESTAMP	 NOT NULL,
	ORG_ID          VARCHAR(36)  NOT NULL
)TABLESPACE CALENDARREGTABSPACE;
CREATE INDEX CALENDAR.CA_EVTAGAGG_CALID_IDX ON CALENDAR.CA_EVENTTAGAGG(CALENDAR_UUID, TOTAL, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE UNIQUE INDEX CALENDAR.CA_EVTAGAGG_CALID_NAME_IDX ON CALENDAR.CA_EVENTTAGAGG(CALENDAR_UUID, NAME, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;

CREATE TABLE CALENDAR.CA_EVENTCOMMENT (
	COMMENT_UUID	VARCHAR(36)	 NOT NULL,
	CALENDAR_UUID	VARCHAR(36)	 NOT NULL,
	EVENT_UUID		VARCHAR(36)	 NOT NULL,
	CREATEDBY		VARCHAR(36)	 NOT NULL,
	CREATEON		TIMESTAMP	 NOT NULL,
	CONTENT	    	CLOB         NOT NULL,
	CONTENTTYPE 	INTEGER 	 DEFAULT 2 NOT NULL,
	ORG_ID          VARCHAR(36)  NOT NULL
)TABLESPACE CALENDARREGTABSPACE;
CREATE INDEX CALENDAR.CA_EVCMT_EVID_IDX ON CALENDAR.CA_EVENTCOMMENT(EVENT_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;

CREATE TABLE CALENDAR.CA_EVENTFOLLOWING (
    EVFLW_UUID		VARCHAR(36)	 NOT NULL,
    CALENDAR_UUID	VARCHAR(36)	 NOT NULL,
    EVENT_UUID		VARCHAR(36)	 NOT NULL,
    EVENTITEM_UUID  VARCHAR(36)  NOT NULL,
    EVENTITEM_TYPE	INTEGER	     NOT NULL, -- 0: event, 1: instance
    ENDDATE			TIMESTAMP	 NOT NULL,
    USER_UUID		VARCHAR(36)	 NOT NULL,
    FOLLOW   		INTEGER	     NOT NULL, -- event 'follow' type, 0x01: follow, 0x02: attend, 0x10: both attend and follow
    MODIFIEDON		TIMESTAMP	 NOT NULL,
    ORG_ID          VARCHAR(36)  NOT NULL
)TABLESPACE CALENDARREGTABSPACE;
CREATE INDEX CALENDAR.CA_EVFLW_CAID_IDX ON CALENDAR.CA_EVENTFOLLOWING(CALENDAR_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVFLW_EVID_IDX ON CALENDAR.CA_EVENTFOLLOWING(EVENT_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE UNIQUE INDEX CALENDAR.CA_EVFLW_EVITEM_IDX ON CALENDAR.CA_EVENTFOLLOWING(EVENTITEM_UUID, EVENTITEM_TYPE, USER_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVFLW_USR_IDX ON CALENDAR.CA_EVENTFOLLOWING(USER_UUID, ENDDATE, FOLLOW, CALENDAR_UUID, EVENTITEM_UUID, EVENTITEM_TYPE, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;

CREATE TABLE CALENDAR.CA_MISCDATA (
    NAME          	VARCHAR(256)  NOT NULL,
    VAL       		VARCHAR(1024) NOT NULL,
    MODIFIEDON		TIMESTAMP	  NOT NULL
)TABLESPACE CALENDARREGTABSPACE;

CREATE TABLE CALENDAR.CA_USERMENTION (
    MENTION_UUID   VARCHAR(48) NOT NULL,
    OBJECT_ID      VARCHAR(48) NOT NULL,
    OBJECT_TYPE    INTEGER NOT NULL, -- 1: event, 2: instance, 3: comment
    CALENDAR_UUID  VARCHAR(48) NOT NULL,
    USER_UUID      VARCHAR(48) NOT NULL, 
    MENTIONEDBY    VARCHAR(48) NOT NULL, 
    CREATEDON      TIMESTAMP   NOT NULL,
    ORG_ID         VARCHAR(36) NOT NULL
)TABLESPACE CALENDARREGTABSPACE;
CREATE INDEX CALENDAR.CA_UM_OBJECT_IDX on CALENDAR.CA_USERMENTION(OBJECT_ID, OBJECT_TYPE, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_UM_USER_IDX on CALENDAR.CA_USERMENTION(USER_UUID, ORG_ID)TABLESPACE CALENDARINDEXTABSPACE;

--------------------------------------
-- PKs
--------------------------------------

ALTER TABLE CALENDAR.CA_SCHEMA
	ADD (CONSTRAINT CA_SCHEMA_PK PRIMARY KEY (COMPKEY) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);

ALTER TABLE CALENDAR.CA_MEMBERSHIP
	ADD (CONSTRAINT CA_MEMBERSHIP_PK PRIMARY KEY (MEMBER_UUID, CALENDAR_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);

ALTER TABLE CALENDAR.CA_CALENDAR
	ADD (CONSTRAINT CA_CALENDAR_PK PRIMARY KEY (CALENDAR_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);
	
ALTER TABLE CALENDAR.CA_RECURRENCE
    ADD (CONSTRAINT CA_RECURRENCE_PK PRIMARY KEY (EVENT_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);

ALTER TABLE CALENDAR.CA_EVENT
    ADD (CONSTRAINT CA_EVENT_PK PRIMARY KEY (EVENT_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);

ALTER TABLE CALENDAR.CA_EVENTINSTANCE
    ADD (CONSTRAINT CA_EVENTINST_PK PRIMARY KEY (EVENTINST_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);

ALTER TABLE CALENDAR.CA_SUBSTITUTION
    ADD (CONSTRAINT CA_SUBSTITUTION_PK PRIMARY KEY (SUBSTITUTION_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);

ALTER TABLE CALENDAR.CA_EVENTINFO
    ADD (CONSTRAINT CA_EVENTINFO_PK PRIMARY KEY (EVENTINFO_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);
    
ALTER TABLE CALENDAR.CA_DELETION_HISTORY
	ADD (CONSTRAINT CA_DELHISTORY_PK PRIMARY KEY (DELHISTORY_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);
	
ALTER TABLE CALENDAR.CA_EVENTTAG 
	ADD (CONSTRAINT CA_EVTAG_PK PRIMARY KEY (TAG_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);

ALTER TABLE CALENDAR.CA_EVENTTAGAGG 
	ADD (CONSTRAINT CA_EVTAGAGG_PK PRIMARY KEY (TAGAGG_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);

ALTER TABLE CALENDAR.CA_EVENTCOMMENT 
	ADD (CONSTRAINT CA_EVCMT_PK PRIMARY KEY (COMMENT_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);
	
ALTER TABLE CALENDAR.CA_EVENTFOLLOWING
	ADD (CONSTRAINT CA_EVFLW_PK PRIMARY KEY (EVFLW_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);

ALTER TABLE CALENDAR.CA_MISCDATA
	ADD (CONSTRAINT CA_MISCDATA_PK PRIMARY KEY (NAME) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);
	
ALTER TABLE CALENDAR.CA_USERMENTION
	ADD (CONSTRAINT CA_USERMENTION_PK PRIMARY KEY (MENTION_UUID, ORG_ID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);
    
--------------------------------------
-- INSERTS
--------------------------------------

INSERT INTO CALENDAR.CA_SCHEMA (COMPKEY, DBSCHEMAVER, RELEASEVER, POSTSCHEMAVER) VALUES ('CALENDAR', '40', '6.0.0.0.0', '40.0');
	
COMMIT;

QUIT;
