-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2011, 2014                       
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_SCHEMA TO SNCOMMUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_MEMBERSHIP TO SNCOMMUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_EVENT TO SNCOMMUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_EVENTINFO TO SNCOMMUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_RECURRENCE TO SNCOMMUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_EVENTINSTANCE TO SNCOMMUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_CALENDAR TO SNCOMMUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_SUBSTITUTION TO SNCOMMUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_DELETION_HISTORY TO SNCOMMUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_EVENTTAG TO SNCOMMUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_EVENTTAGAGG TO SNCOMMUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_EVENTCOMMENT TO SNCOMMUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_EVENTFOLLOWING TO SNCOMMUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_MISCDATA TO SNCOMMUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_USERMENTION TO SNCOMMUSER_ROLE;

GRANT SELECT ON SNCOMM.MEMBERPROFILE TO CALENDAR WITH GRANT OPTION;
GRANT SELECT ON CALENDAR.CA_USER TO SNCOMMUSER_ROLE;

COMMIT;

QUIT;

