-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2011                            
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

UPDATE CALENDAR.CA_SCHEMA SET DBSCHEMAVER = '10', RELEASEVER = '4.0.0.0.0' WHERE COMPKEY = 'CALENDAR';

ALTER TABLE CALENDAR.CA_CALENDAR ADD (CREATEDON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL); 
ALTER TABLE CALENDAR.CA_CALENDAR ADD (ACLMODTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL); 
ALTER TABLE CALENDAR.CA_SUBSTITUTION ADD (MODIFIEDON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL); 
ALTER TABLE CALENDAR.CA_RECURRENCE ADD (MODIFIEDON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL); 

CREATE INDEX CALENDAR.CA_CAL_DBMODTIME_IDX ON CALENDAR.CA_CALENDAR(ACLMODTIME, CREATEDON)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EV_MODITIME_IDX ON CALENDAR.CA_EVENT(MODIFIEDON)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_SUB_MODITIME_IDX ON CALENDAR.CA_SUBSTITUTION(MODIFIEDON, EVENTINFO_UUID, ISCANCELLED)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_RECUR_MODITIME_IDX ON CALENDAR.CA_RECURRENCE(MODIFIEDON)TABLESPACE CALENDARINDEXTABSPACE;

CREATE TABLE CALENDAR.CA_DELETION_HISTORY (
	DELHISTORY_UUID	VARCHAR(36)	NOT NULL,	
	OBJECT_TYPE		INTEGER 	NOT NULL, -- 0 - EVENT, 1 - EXCEPTION INSTANCE
	OBJECT_UUID		VARCHAR(36) NOT NULL,
	DBMODTIME		TIMESTAMP	NOT NULL
)TABLESPACE CALENDARREGTABSPACE;
CREATE INDEX CALENDAR.CA_DELHIS_TIME_IDX ON CALENDAR.CA_DELETION_HISTORY(DBMODTIME)TABLESPACE CALENDARINDEXTABSPACE;

ALTER TABLE CALENDAR.CA_DELETION_HISTORY
	ADD (CONSTRAINT CA_DELHISTORY_PK PRIMARY KEY (DELHISTORY_UUID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);
	
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_DELETION_HISTORY TO SNCOMMUSER_ROLE;

-- 20110711, fixup03
ALTER TABLE CALENDAR.CA_CALENDAR ADD (WIDGETID VARCHAR(48));

-- 20110711, fixup04
CREATE TABLE CALENDAR.CA_EVENTTAG (
	TAG_UUID		VARCHAR(36)	 NOT NULL,
	CALENDAR_UUID	VARCHAR(36)	 NOT NULL,
	EVENT_UUID		VARCHAR(36)	 NOT NULL,
	NAME	    	VARCHAR(256) NOT NULL,
	MODIFIEDON	    TIMESTAMP	 NOT NULL
)TABLESPACE CALENDARREGTABSPACE;
CREATE INDEX CALENDAR.CA_EVTAG_EVID_IDX ON CALENDAR.CA_EVENTTAG(EVENT_UUID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVTAG_CALID_IDX ON CALENDAR.CA_EVENTTAG(CALENDAR_UUID, NAME)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVTAG_NAME_IDX ON CALENDAR.CA_EVENTTAG(NAME, CALENDAR_UUID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE UNIQUE INDEX CALENDAR.CA_EVTAG_NAME_EVID_IDX ON CALENDAR.CA_EVENTTAG(NAME, EVENT_UUID)TABLESPACE CALENDARINDEXTABSPACE;

CREATE TABLE CALENDAR.CA_EVENTTAGAGG (
	TAGAGG_UUID		VARCHAR(36)	 NOT NULL,
	CALENDAR_UUID	VARCHAR(36),
	NAME	    	VARCHAR(256) NOT NULL,
	TOTAL			INTEGER		 NOT NULL,
	LASTUSED	    TIMESTAMP	 NOT NULL
)TABLESPACE CALENDARREGTABSPACE;
CREATE INDEX CALENDAR.CA_EVTAGAGG_CALID_IDX ON CALENDAR.CA_EVENTTAGAGG(CALENDAR_UUID, TOTAL)TABLESPACE CALENDARINDEXTABSPACE;
CREATE UNIQUE INDEX CALENDAR.CA_EVTAGAGG_CALID_NAME_IDX ON CALENDAR.CA_EVENTTAGAGG(CALENDAR_UUID, NAME)TABLESPACE CALENDARINDEXTABSPACE;

CREATE TABLE CALENDAR.CA_EVENTCOMMENT (
	COMMENT_UUID	VARCHAR(36)	 NOT NULL,
	CALENDAR_UUID	VARCHAR(36)	 NOT NULL,
	EVENT_UUID		VARCHAR(36)	 NOT NULL,
	CREATEDBY		VARCHAR(36)	 NOT NULL,
	CREATEON		TIMESTAMP	 NOT NULL,
	CONTENT	    	CLOB         NOT NULL
)TABLESPACE CALENDARREGTABSPACE;
CREATE INDEX CALENDAR.CA_EVCMT_EVID_IDX ON CALENDAR.CA_EVENTCOMMENT(EVENT_UUID)TABLESPACE CALENDARINDEXTABSPACE;

ALTER TABLE CALENDAR.CA_EVENTTAG 
	ADD (CONSTRAINT CA_EVTAG_PK PRIMARY KEY (TAG_UUID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);

ALTER TABLE CALENDAR.CA_EVENTTAGAGG 
	ADD (CONSTRAINT CA_EVTAGAGG_PK PRIMARY KEY (TAGAGG_UUID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);

ALTER TABLE CALENDAR.CA_EVENTCOMMENT 
	ADD (CONSTRAINT CA_EVCMT_PK PRIMARY KEY (COMMENT_UUID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);
	
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_EVENTTAG TO SNCOMMUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_EVENTTAGAGG TO SNCOMMUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_EVENTCOMMENT TO SNCOMMUSER_ROLE;

-- 20110721, fixup05
ALTER TABLE CALENDAR.CA_EVENT ADD (DBMODTIME TIMESTAMP);
CREATE INDEX CALENDAR.CA_EV_DBMODTIME_IDX ON CALENDAR.CA_EVENT(DBMODTIME)TABLESPACE CALENDARINDEXTABSPACE;

-- 20110802, fixup06
ALTER TABLE CALENDAR.CA_EVENTINSTANCE ADD (MODIFIEDBY VARCHAR(36));
ALTER TABLE CALENDAR.CA_EVENTINSTANCE ADD (MODIFIEDON TIMESTAMP);

-- 20110817, fixup07
ALTER TABLE CALENDAR.CA_EVENTINFO ADD (IMAGE_URL VARCHAR(1024));

-- 20110821, fixup08
CREATE INDEX CALENDAR.CA_CAL_VISIBILITY_IDX ON CALENDAR.CA_CALENDAR(CALENDAR_UUID, VISIBILITY)TABLESPACE CALENDARINDEXTABSPACE;

DROP INDEX CALENDAR.CA_EV_CALID_IDX;
CREATE INDEX CALENDAR.CA_EV_CALID_IDX ON CALENDAR.CA_EVENT(CALENDAR_UUID, CREATEDON DESC)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EV_USERID_IDX ON CALENDAR.CA_EVENT(CREATEDBY, CREATEDON DESC)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EV_CALID_USERID_IDX ON CALENDAR.CA_EVENT(CALENDAR_UUID, CREATEDBY, CREATEDON DESC)TABLESPACE CALENDARINDEXTABSPACE;

-- 20110921, fixup09
DROP INDEX CALENDAR.CA_EVINST_CALID_SD_IDX;

CREATE INDEX CALENDAR.CA_EVINST_CALID_EDSD_IDX ON CALENDAR.CA_EVENTINSTANCE(CALENDAR_UUID, ENDDATE, STARTDATE)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVINST_EVID_EDSD_IDX ON CALENDAR.CA_EVENTINSTANCE(EVENT_UUID, ENDDATE DESC, STARTDATE)TABLESPACE CALENDARINDEXTABSPACE;
CREATE UNIQUE INDEX CALENDAR.CA_EVINST_INST_EDSD_IDX ON CALENDAR.CA_EVENTINSTANCE(EVENTINST_UUID, ENDDATE, STARTDATE)TABLESPACE CALENDARINDEXTABSPACE;

CREATE TABLE CALENDAR.CA_EVENTFOLLOWING (
    EVFLW_UUID		VARCHAR(36)	 NOT NULL,
    CALENDAR_UUID	VARCHAR(36)	 NOT NULL,
    EVENT_UUID		VARCHAR(36)	 NOT NULL,
    EVENTITEM_UUID  VARCHAR(36)  NOT NULL,
    EVENTITEM_TYPE	INTEGER	     NOT NULL, -- 0: event, 1: instance
    ENDDATE			TIMESTAMP	 NOT NULL,
    USER_UUID		VARCHAR(36)	 NOT NULL,
    FOLLOW   		INTEGER	     NOT NULL, -- event 'follow' type, 0x01: follow, 0x02: attend, 0x10: both attend and follow
    MODIFIEDON		TIMESTAMP	 NOT NULL
)TABLESPACE CALENDARREGTABSPACE;
CREATE INDEX CALENDAR.CA_EVFLW_CAID_IDX ON CALENDAR.CA_EVENTFOLLOWING(CALENDAR_UUID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVFLW_EVID_IDX ON CALENDAR.CA_EVENTFOLLOWING(EVENT_UUID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE UNIQUE INDEX CALENDAR.CA_EVFLW_EVITEM_IDX ON CALENDAR.CA_EVENTFOLLOWING(EVENTITEM_UUID, EVENTITEM_TYPE, USER_UUID)TABLESPACE CALENDARINDEXTABSPACE;
CREATE INDEX CALENDAR.CA_EVFLW_USR_IDX ON CALENDAR.CA_EVENTFOLLOWING(USER_UUID, ENDDATE, FOLLOW, CALENDAR_UUID, EVENTITEM_UUID, EVENTITEM_TYPE)TABLESPACE CALENDARINDEXTABSPACE;

CREATE TABLE CALENDAR.CA_MISCDATA (
    NAME          	VARCHAR(256)  NOT NULL,
    VAL       		VARCHAR(1024) NOT NULL,
    MODIFIEDON		TIMESTAMP	  NOT NULL
)TABLESPACE CALENDARREGTABSPACE;

ALTER TABLE CALENDAR.CA_EVENTFOLLOWING
	ADD (CONSTRAINT CA_EVFLW_PK PRIMARY KEY (EVFLW_UUID) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);

ALTER TABLE CALENDAR.CA_MISCDATA
	ADD (CONSTRAINT CA_MISCDATA_PK PRIMARY KEY (NAME) USING INDEX TABLESPACE CALENDARINDEXTABSPACE);
	
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_EVENTFOLLOWING TO SNCOMMUSER_ROLE;
GRANT INSERT,UPDATE,SELECT,DELETE ON CALENDAR.CA_MISCDATA TO SNCOMMUSER_ROLE;

COMMIT;

QUIT;