-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2011                           
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

--------------------------------------
-- CONNECT TO SNCOMM
--------------------------------------
USE SNCOMM;
GO

BEGIN TRANSACTION;

UPDATE CALENDAR.CA_SCHEMA SET DBSCHEMAVER = '10', RELEASEVER = '4.0.0.0.0' WHERE COMPKEY = 'CALENDAR';

ALTER TABLE CALENDAR.CA_CALENDAR ADD CREATEDON DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL; 
ALTER TABLE CALENDAR.CA_CALENDAR ADD ACLMODTIME DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL; 
ALTER TABLE CALENDAR.CA_SUBSTITUTION ADD MODIFIEDON DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL; 
ALTER TABLE CALENDAR.CA_RECURRENCE ADD MODIFIEDON DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL; 

CREATE INDEX CA_CAL_ACLMODTIME_IDX ON CALENDAR.CA_CALENDAR(ACLMODTIME, CREATEDON);
CREATE INDEX CA_EV_MODITIME_IDX ON CALENDAR.CA_EVENT(MODIFIEDON);
CREATE INDEX CA_SUB_MODITIME_IDX ON CALENDAR.CA_SUBSTITUTION(MODIFIEDON, EVENTINFO_UUID, ISCANCELLED);
CREATE INDEX CA_RECUR_MODITIME_IDX ON CALENDAR.CA_RECURRENCE(MODIFIEDON);

CREATE TABLE CALENDAR.CA_DELETION_HISTORY (
	DELHISTORY_UUID	NVARCHAR(36)	NOT NULL,	
	OBJECT_TYPE		INTEGER 		NOT NULL, -- 0 - EVENT, 1 - EXCEPTION INSTANCE
	OBJECT_UUID		NVARCHAR(36) 	NOT NULL,
	DBMODTIME		DATETIME		NOT NULL
);
CREATE INDEX CA_DELHIS_TIME_IDX ON CALENDAR.CA_DELETION_HISTORY(DBMODTIME);

ALTER TABLE CALENDAR.CA_DELETION_HISTORY
ADD CONSTRAINT CA_DELHISTORY_PK PRIMARY KEY (
	DELHISTORY_UUID
);

GRANT DELETE,INSERT,SELECT,UPDATE ON CALENDAR.CA_DELETION_HISTORY TO SNCOMMUSER;

-- 20110711, fixup03
ALTER TABLE CALENDAR.CA_CALENDAR ADD WIDGETID NVARCHAR(48); 

-- 20110711, fixup04
CREATE TABLE CALENDAR.CA_EVENTTAG (
	TAG_UUID		NVARCHAR(36)	 NOT NULL,
	CALENDAR_UUID	NVARCHAR(36)	 NOT NULL,
	EVENT_UUID		NVARCHAR(36)	 NOT NULL,
	NAME	    	NVARCHAR(256) 	 NOT NULL,
	MODIFIEDON	    DATETIME	 	 NOT NULL
);
CREATE INDEX CA_EVTAG_EVID_IDX ON CALENDAR.CA_EVENTTAG(EVENT_UUID);
CREATE INDEX CA_EVTAG_CALID_IDX ON CALENDAR.CA_EVENTTAG(CALENDAR_UUID, NAME);
CREATE INDEX CA_EVTAG_NAME_IDX ON CALENDAR.CA_EVENTTAG(NAME, CALENDAR_UUID);
CREATE UNIQUE INDEX CA_EVTAG_NAME_EVID_IDX ON CALENDAR.CA_EVENTTAG(NAME, EVENT_UUID);

CREATE TABLE CALENDAR.CA_EVENTTAGAGG (
	TAGAGG_UUID		NVARCHAR(36)	 NOT NULL,
	CALENDAR_UUID	NVARCHAR(36),
	NAME	    	NVARCHAR(256) 	 NOT NULL,
	TOTAL			INTEGER		 	 NOT NULL,
	LASTUSED	    DATETIME	 	 NOT NULL
);
CREATE INDEX CA_EVTAGAGG_CALID_IDX ON CALENDAR.CA_EVENTTAGAGG(CALENDAR_UUID, TOTAL);
CREATE UNIQUE INDEX CA_EVTAGAGG_CALID_NAME_IDX ON CALENDAR.CA_EVENTTAGAGG(CALENDAR_UUID, NAME);

CREATE TABLE CALENDAR.CA_EVENTCOMMENT (
	COMMENT_UUID	NVARCHAR(36)	 NOT NULL,
	CALENDAR_UUID	NVARCHAR(36)	 NOT NULL,
	EVENT_UUID		NVARCHAR(36)	 NOT NULL,
	CREATEDBY		NVARCHAR(36)	 NOT NULL,
	CREATEON		DATETIME	 	 NOT NULL,
	CONTENT	    	NVARCHAR(MAX) 	 NOT NULL
);
CREATE INDEX CA_EVCMT_EVID_IDX ON CALENDAR.CA_EVENTCOMMENT(EVENT_UUID);

ALTER TABLE CALENDAR.CA_EVENTTAG
ADD CONSTRAINT CA_EVTAG_PK PRIMARY KEY (
	TAG_UUID
);

ALTER TABLE CALENDAR.CA_EVENTTAGAGG
ADD CONSTRAINT CA_EVTAGAGG_PK PRIMARY KEY (
	TAGAGG_UUID
);

ALTER TABLE CALENDAR.CA_EVENTCOMMENT
ADD CONSTRAINT CA_EVCMT_PK PRIMARY KEY (
	COMMENT_UUID
);

GRANT DELETE,INSERT,SELECT,UPDATE ON CALENDAR.CA_EVENTTAG TO SNCOMMUSER;
GRANT DELETE,INSERT,SELECT,UPDATE ON CALENDAR.CA_EVENTTAGAGG TO SNCOMMUSER;
GRANT DELETE,INSERT,SELECT,UPDATE ON CALENDAR.CA_EVENTCOMMENT TO SNCOMMUSER;

-- 20110721, fixup05
ALTER TABLE CALENDAR.CA_EVENT ADD DBMODTIME DATETIME;
CREATE INDEX CA_EV_DBMODTIME_IDX ON CALENDAR.CA_EVENT(DBMODTIME);

-- 20110802, fixup06
ALTER TABLE CALENDAR.CA_EVENTINSTANCE ADD MODIFIEDBY NVARCHAR(36); 
ALTER TABLE CALENDAR.CA_EVENTINSTANCE ADD MODIFIEDON DATETIME;

-- 20110817, fixup07
ALTER TABLE CALENDAR.CA_EVENTINFO ADD IMAGE_URL NVARCHAR(1024);

-- 20110821, fixup08
CREATE INDEX CA_CAL_VISIBILITY_IDX ON CALENDAR.CA_CALENDAR(CALENDAR_UUID, VISIBILITY);

DROP INDEX CA_EV_CALID_IDX ON CALENDAR.CA_EVENT;
CREATE INDEX CA_EV_CALID_IDX ON CALENDAR.CA_EVENT(CALENDAR_UUID, CREATEDON DESC);
CREATE INDEX CA_EV_USERID_IDX ON CALENDAR.CA_EVENT(CREATEDBY, CREATEDON DESC);
CREATE INDEX CA_EV_CALID_USERID_IDX ON CALENDAR.CA_EVENT(CALENDAR_UUID, CREATEDBY, CREATEDON DESC);

-- 20110921, fixup09
DROP INDEX CA_EVINST_CALID_SD_IDX ON CALENDAR.CA_EVENTINSTANCE;

CREATE INDEX CA_EVINST_CALID_EDSD_IDX ON CALENDAR.CA_EVENTINSTANCE(CALENDAR_UUID, ENDDATE, STARTDATE);
CREATE INDEX CA_EVINST_EVID_EDSD_IDX ON CALENDAR.CA_EVENTINSTANCE(EVENT_UUID, ENDDATE DESC, STARTDATE);
CREATE UNIQUE INDEX CA_EVINST_INST_EDSD_IDX ON CALENDAR.CA_EVENTINSTANCE(EVENTINST_UUID, ENDDATE, STARTDATE);

CREATE TABLE CALENDAR.CA_EVENTFOLLOWING (
    EVFLW_UUID		NVARCHAR(36)	 NOT NULL,
    CALENDAR_UUID	NVARCHAR(36)	 NOT NULL,
    EVENT_UUID		NVARCHAR(36)	 NOT NULL,
    EVENTITEM_UUID  NVARCHAR(36)  	 NOT NULL,
    EVENTITEM_TYPE	INTEGER	     	 NOT NULL, -- 0: event, 1: instance
    ENDDATE			DATETIME	 	 NOT NULL,
    USER_UUID		NVARCHAR(36)	 NOT NULL,
    FOLLOW   		INTEGER	     	 NOT NULL, -- event 'follow' type, 0x01: follow, 0x02: attend, 0x10: both attend and follow
    MODIFIEDON		DATETIME	 	 NOT NULL
);
CREATE INDEX CA_EVFLW_CAID_IDX ON CALENDAR.CA_EVENTFOLLOWING(CALENDAR_UUID);
CREATE INDEX CA_EVFLW_EVID_IDX ON CALENDAR.CA_EVENTFOLLOWING(EVENT_UUID);
CREATE UNIQUE INDEX CA_EVFLW_EVITEM_IDX ON CALENDAR.CA_EVENTFOLLOWING(EVENTITEM_UUID, EVENTITEM_TYPE, USER_UUID);
CREATE UNIQUE INDEX CA_EVFLW_USR_IDX ON CALENDAR.CA_EVENTFOLLOWING(USER_UUID, ENDDATE, EVFLW_UUID) INCLUDE (FOLLOW, CALENDAR_UUID, EVENTITEM_UUID, EVENTITEM_TYPE);

CREATE TABLE CALENDAR.CA_MISCDATA (
    NAME          	NVARCHAR(256)  NOT NULL,
    VAL       		NVARCHAR(1024) NOT NULL,
    MODIFIEDON		DATETIME	   NOT NULL
);

ALTER TABLE CALENDAR.CA_EVENTFOLLOWING
ADD CONSTRAINT CA_EVFLW_PK PRIMARY KEY (
	EVFLW_UUID
);

ALTER TABLE CALENDAR.CA_MISCDATA
ADD CONSTRAINT CA_MISCDATA_PK PRIMARY KEY (
	NAME
);

GRANT DELETE,INSERT,SELECT,UPDATE ON CALENDAR.CA_EVENTFOLLOWING TO SNCOMMUSER;
GRANT DELETE,INSERT,SELECT,UPDATE ON CALENDAR.CA_MISCDATA TO SNCOMMUSER;

COMMIT;